<?php
// Specialty page data — ported from assets/js/specialty-data.jsx
// One entry per specialty slug. Used by gps.php, dentists.php, etc.

return [
    'dental' => [
        'slug' => 'dentists',
        'label' => 'Dentists',
        'icon' => '🦷',
        'headline' => ['A clinic OS that thinks in ', 'teeth', ', not in spreadsheets.'],
        'heroBlurb' => 'Visual charting, treatment plans your patients understand, and recall that runs itself. Built with dentists in 14 countries.',
        'heroProof' => ['412 dental clinics', '14 countries', 'From $13/mo'],
        'stats' => [['+71%', 'Recall rate vs paper'], ['+30%', 'Treatment-plan acceptance'], ['−42%', 'Time charting per patient'], ['4.9', 'Avg dentist rating']],
        'featsHead' => ['Six things every dental clinic needs.', "None of the stuff you don't."],
        'feats' => [
            ['🦷', 'Visual dental chart', 'FDI, Palmer, or Universal numbering. Tap a tooth — see every note, image, and procedure since the first visit.'],
            ['🖼️', 'Per-tooth imaging', 'X-rays, intraoral photos, scans — attach to a tooth, a quadrant, or the whole arch. Drag, drop, done.'],
            ['🧾', 'Treatment plans + quotes', 'Plan a course of work, send a quote your patient can accept on WhatsApp, track each visit against it.'],
            ['📅', 'Recall by procedure', '6-month cleanings, 3-month perio, annual whitening — auto-scheduled reminders that book themselves.'],
            ['℞', 'Dental-specific Rx', 'Antibiotics, analgesics, fluoride — pre-loaded with dose templates dental colleges actually use.'],
            ['💊', 'Implant & material inventory', 'Track every implant by lot. Expiry alerts before the next big patient lands in your chair.'],
        ],
        'workflowHead' => 'From check-in to recall, in five steps.',
        'workflow' => [
            ['Patient arrives', 'Receptionist scans the QR card. Chart loads with last visit, allergies, payment status.'],
            ['You chart in the chair', 'Open the dental chart on iPad. Tap tooth 16, mark a caries class II, attach a photo — 20 seconds.'],
            ['Build the plan', 'Drag procedures into a multi-visit treatment plan with materials and time blocks.'],
            ['Quote sent on WhatsApp', 'Patient gets a clean PDF with line items, total, and an "Accept & book" link. No printer.'],
            ['Recall, automated', 'Six months later, the system books them in for cleaning and sends the reminder.'],
        ],
        'pricingHead' => 'A real dental clinic, $33 a month.',
        'pricingBlurb' => "Most single-chair dentists run on Starter plus a few targeted modules. Here's a real configuration.",
        'pricingLabel' => 'Single-chair dental clinic',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Dental charting module', '$9/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Billing & invoices', '$9/mo'],
            ['Analytics', '$9/mo'],
        ],
        'pricingTotal' => 33,
        'testimonialsHead' => 'What dentists say.',
        'testimonials' => [
            ['Dr. James Whitfield', 'Toronto, Canada', 'I ran paper-and-Excel chairside for 14 years. We switched in a long weekend and our recall rate went from 38% to 71% in the first quarter.'],
            ['Dr. Ananya Rao', 'Bangalore, India', 'The treatment plan PDF is so clean my patients actually read it. Case acceptance up 30%.'],
            ['Dr. Yusuf El-Sayed', 'Dubai, UAE', 'Multilingual quotes in English and Arabic with the right insurance codes. Nothing else does this for under $100/month.'],
        ],
        'migrationBlurb' => 'If you have over 500 records, our team handles migration end-to-end. We import from any of the systems below — and most spreadsheets.',
        'migrateFrom' => ['Dentrix', 'Eaglesoft', 'Open Dental', 'Curve', 'Practo', 'Cliniko', 'Drchrono', 'SimplePractice', 'Excel / CSV', 'Paper register'],
        'ctaTitle' => 'Run a dental clinic that thinks in teeth.',
        'ctaSub' => "Start free. Add the dental module when you're ready.",
    ],

    'gp' => [
        'slug' => 'gps',
        'label' => 'GPs',
        'icon' => '🩺',
        'headline' => ['For the everyday doctor, ', 'finally', ' given great tools.'],
        'heroBlurb' => 'OPD-ready out of the box. Triage, vitals, common Rx templates, and a fast walk-in flow — the GP basics, beautifully.',
        'heroProof' => ['1,420 GP clinics', '32 countries', 'From $15/mo'],
        'stats' => [['8 min', 'Avg wait time saved'], ['−55%', 'Time at front desk'], ['+22%', 'Repeat visit rate'], ['4.8', 'Avg GP rating']],
        'featsHead' => ['Built for the rhythm of a busy OPD.', 'Triage, treat, recall.'],
        'feats' => [
            ['⚡', 'Walk-in triage', 'Add a walk-in in 5 seconds with severity. The queue updates everyone in real time.'],
            ['📈', 'Vitals on entry', "Nurse captures vitals on a tablet. They're on your screen by the time the patient sits down."],
            ['℞', 'Top-200 Rx templates', 'Pre-built scripts for the top 200 conditions. Sign with one tap, edit when needed.'],
            ['📋', 'Chronic care timelines', 'HTN, diabetes, COPD — one timeline view with target bands and overdue checks.'],
            ['👨‍👩‍👧', 'Family history', 'A clean visual family tree with hereditary tagging. Builds itself from each visit.'],
            ['💬', 'Post-visit summary', 'Patients get a clean summary on WhatsApp before they get to the car park.'],
        ],
        'workflowHead' => 'A 10-minute OPD visit, end to end.',
        'workflow' => [
            ['Walk-in or arrives', 'Receptionist tags severity. Patient enters queue with a live wait estimate.'],
            ['Vitals captured', 'Nurse records BP, HR, weight on tablet. Flagged in red if outside the target band.'],
            ['Doctor reviews', 'You see vitals, last visit, allergies and the suggested Rx template all on one screen.'],
            ['Rx + visit notes', 'One tap to sign Rx. Voice-dictate visit notes or type in SOAP.'],
            ['Summary delivered', 'WhatsApp summary, follow-up booked, billing reconciled before they leave.'],
        ],
        'pricingHead' => 'A real solo GP, $24 a month.',
        'pricingBlurb' => "Most solo GPs run on Starter plus the essentials. Pay nothing for the chronic-care features you don't use yet.",
        'pricingLabel' => 'Solo GP, ~25 patients/day',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Digital prescriptions', '$6/mo'],
            ['QR patient card', '$4/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 24,
        'testimonialsHead' => 'What GPs say.',
        'testimonials' => [
            ['Dr. Aarav Sharma', 'Mumbai, India', 'I switched from paper in two weekends. The QR cards alone cut my check-in time by 80%. My nurses cried with joy.'],
            ['Dr. Ben Carter', 'Bristol, UK', 'Calm, fast, no junk. It feels like a tool made for clinicians, not for the people selling to clinicians.'],
            ['Dr. Liang Wei', 'Singapore', 'I see 40 patients a day. The vitals trend chart catches things I would have missed flipping through paper.'],
        ],
        'migrationBlurb' => 'Coming from EMRs, paper, or a tangle of spreadsheets — we move it all. Most clinics are live in under a week.',
        'migrateFrom' => ['Practo', 'Drchrono', 'Athenahealth', 'eClinicalWorks', 'EMIS', 'SystmOne', 'Cliniko', 'SimplePractice', 'Excel / CSV', 'Paper register'],
        'ctaTitle' => 'Run a GP practice that respects your time.',
        'ctaSub' => 'Start free. Add modules when your day demands it.',
    ],

    'homeo' => [
        'slug' => 'homeopaths',
        'label' => 'Homeopaths',
        'icon' => '🌿',
        'headline' => ['Built for ', 'case taking', ', not just clicking.'],
        'heroBlurb' => 'Long-form repertory notes, a 3,200-remedy database, potency picker, and antidote warnings. The first software a homeopath might actually love.',
        'heroProof' => ['620 homeo clinics', '11 countries', 'From $13/mo'],
        'stats' => [['3,200', 'Remedies in database'], ['15 min', 'Saved per case'], ['6 mo', 'Follow-up tracking'], ['4.9', 'Avg homeopath rating']],
        'featsHead' => ['A clinic OS that speaks homeopathy.', 'Not a generic record system in disguise.'],
        'feats' => [
            ['🧫', 'Remedy database', '3,200 remedies with potency, antidotes, miasm tags and Materia Medica references. Searchable in seconds.'],
            ['📋', 'Repertory case taking', 'A real long-form template — mental generals, physical generals, particulars, modalities — built in.'],
            ['⚡', 'Potency picker', '6X to 1M with a sliding scale. Notes on prescribed potency travel with the case.'],
            ['🛡️', 'Antidote engine', 'Coffee, camphor, peppermint — the system warns when antidotes appear in another part of the chart.'],
            ['📅', 'Follow-up scheduler', 'Three weeks, six weeks, three months — your follow-up cadence built into the calendar.'],
            ['📈', 'Case history view', 'Every remedy ever given, every reaction, every modality change — in one scrollable timeline.'],
        ],
        'workflowHead' => 'From first interview to long-term follow-up.',
        'workflow' => [
            ['First interview', 'Long-form template loads. You take a 60-minute case with mental, physical, particular sections.'],
            ['Repertorize', 'Pick rubrics from the case. The remedy DB suggests top matches with confidence scoring.'],
            ['Prescribe', 'Select remedy, potency, schedule. Antidote warnings surface if anything conflicts.'],
            ['Follow-up books itself', 'System schedules 3-week and 6-week follow-ups, sends WhatsApp reminders.'],
            ['Track over months', 'Every change rolled into a timeline. You see the case story at a glance.'],
        ],
        'pricingHead' => 'A real homeopath, $22 a month.',
        'pricingBlurb' => 'Most solo homeopaths run on Starter plus the remedy database. The rest is free.',
        'pricingLabel' => 'Solo homeopath',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Remedy database', '$7/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 22,
        'testimonialsHead' => 'What homeopaths say.',
        'testimonials' => [
            ['Dr. Priya Iyer', 'Pune, India', 'Finally, software that knows what a repertory case-taking sheet looks like. The remedy DB is shockingly thorough.'],
            ['Dr. Elena Costa', 'Lisbon, Portugal', 'The antidote warnings have saved me three times in the first month. Worth the cost a hundred times over.'],
            ['Dr. Rohit Kapoor', 'Delhi, India', "Long-form case notes that don't fight me. I take cases the way I was taught, not the way the software demands."],
        ],
        'migrationBlurb' => 'Most homeopaths come from paper case books or Word documents. We OCR your old cases and import them, attribute by attribute.',
        'migrateFrom' => ['Paper case books', 'Word / PDF cases', 'Practo', 'Cliniko', 'HomeoSoft', 'Excel / CSV', 'RADAR exports'],
        'ctaTitle' => 'Run a homeo practice that respects the case.',
        'ctaSub' => 'Start free. Turn on the remedy DB when you take your first case.',
    ],

    'derma' => [
        'slug' => 'dermatologists',
        'label' => 'Dermatologists',
        'icon' => '✨',
        'headline' => ['Before, after, and ', 'everything', ' in between.'],
        'heroBlurb' => 'Photo timelines per body area, side-by-side compare, lesion measurement, and consent forms — built for skin, not bent into it.',
        'heroProof' => ['380 derma clinics', '18 countries', 'From $20/mo'],
        'stats' => [['+44%', 'Patient retention'], ['−60%', 'Photo admin time'], ['3D', 'Body-map zones'], ['4.9', 'Avg derma rating']],
        'featsHead' => ['The visual tools dermatology needs.', 'Nothing more, nothing less.'],
        'feats' => [
            ['🖼️', 'Body-map photo logging', 'Tap a body region, attach photos. They organize themselves by area and date forever.'],
            ['🔍', 'Side-by-side compare', 'Pull any two visits next to each other. Slide to wipe between. Patients see progress in 5 seconds.'],
            ['📐', 'Lesion measurement', 'Draw a contour, get area, diameter, asymmetry. Track all four ABCD criteria per lesion.'],
            ['📋', 'Procedure-linked consent', 'Each procedure brings its consent form. Patient signs on tablet, signed PDF lives in the chart.'],
            ['🥗', 'Topical & systemic plans', 'Sequenced treatment plans with photos at each phase. Auto-reminders for application steps.'],
            ['℞', 'Derma-aware Rx', 'Steroid potency ladder, biologics scheduling, retinoid pregnancy warnings built into the workflow.'],
        ],
        'workflowHead' => 'From first photo to twelve-month outcome.',
        'workflow' => [
            ['New patient, body map', 'Tap the regions of concern. Attach phone photos directly to those zones.'],
            ['Diagnose & plan', 'Make the diagnosis, link to procedure consent. Patient signs on the tablet.'],
            ['Procedure or Rx', 'Procedure room: log start/end, materials. Or send the topical Rx via WhatsApp.'],
            ['Follow-up photos', 'Each follow-up auto-aligns photos to the same body-map zone. No more "wait, what angle was this?"'],
            ['Compare & decide', 'Side-by-side wipe between any two visits. Adjust plan, repeat.'],
        ],
        'pricingHead' => 'A real derma clinic, $34 a month.',
        'pricingBlurb' => 'Most dermatologists run the skin imaging module plus the essentials.',
        'pricingLabel' => 'Solo dermatologist',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Skin imaging module', '$11/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
            ['Diet plans', '$3/mo (add-on)'],
        ],
        'pricingTotal' => 34,
        'testimonialsHead' => 'What dermatologists say.',
        'testimonials' => [
            ['Dr. Sofia Marín', 'Madrid, Spain', 'The before/after compare convinced me to stay. The pricing convinced my accountant. We pay €34/month for what we use.'],
            ['Dr. Hannah Lin', 'Sydney, Australia', 'The lesion measurement tool is genuinely better than what we used at the hospital. Patients trust the numbers.'],
            ['Dr. Olu Adebayo', 'Lagos, Nigeria', 'My patients see the progress and stay the full course. Retention jumped from 60% to 88% in six months.'],
        ],
        'migrationBlurb' => 'Skin photos live everywhere — phones, drives, EMRs. We pull them all into the body-map, sorted by date and region.',
        'migrateFrom' => ['NextGen', 'ModMed', 'Mirror Medical', 'Canfield', 'Phone camera roll', 'Google Photos', 'Practo', 'Cliniko', 'Excel / CSV'],
        'ctaTitle' => 'Run a derma clinic that shows the change.',
        'ctaSub' => 'Start free. Turn on skin imaging when your first patient walks in.',
    ],

    'peds' => [
        'slug' => 'pediatricians',
        'label' => 'Pediatricians',
        'icon' => '👶',
        'headline' => ['Watch them grow, on ', 'real percentile', ' curves.'],
        'heroBlurb' => 'WHO growth charts, vaccination scheduler, weight-based dosing, parent-facing summaries — designed around how kids actually grow.',
        'heroProof' => ['540 peds clinics', '22 countries', 'From $19/mo'],
        'stats' => [['+38%', 'Vaccine on-time rate'], ['0', 'Dosing errors logged'], ['12 mo', 'Growth tracking'], ['4.9', 'Avg parent rating']],
        'featsHead' => ['Pediatric care, tooled properly.', 'For every child, from 0 to 18.'],
        'feats' => [
            ['🌱', 'WHO growth charts', 'Weight, height, head circumference, BMI — every visit plotted on WHO percentile bands.'],
            ['📅', 'Vaccine scheduler', "Country-specific schedules. Reminders go to the parent's WhatsApp 30 days before each dose."],
            ['℞', 'Weight-based dosing', "Enter the child's weight; doses calculate themselves. Pediatric range warnings catch outliers."],
            ['💬', 'Parent-facing summaries', 'After each visit, parents get a clean summary in plain language with next steps.'],
            ['📋', 'Developmental milestones', 'Auto-prompted milestone checks at 2/4/6/9/12/18/24-month visits. Track delays cleanly.'],
            ['🛡️', 'Allergy & feeding flags', 'Penicillin, peanut, lactose, gluten — flagged across every Rx and procedure.'],
        ],
        'workflowHead' => 'Every well-visit, the same five-step rhythm.',
        'workflow' => [
            ['Weigh & measure', 'Nurse enters weight, height, head circumference on tablet. Auto-plotted on percentile curve.'],
            ['Milestone check', 'System prompts the right age-appropriate milestones. You tap "met" or add notes.'],
            ['Vaccine review', "Schedule shows what's due today, what's coming up next month, what got missed."],
            ['Rx with auto-dose', 'Type the drug name; dose, frequency, and duration calculate from the latest weight.'],
            ['Parent summary', 'WhatsApp summary goes out: "You saw Dr. Okonkwo today. Sneha is at the 62nd percentile…"'],
        ],
        'pricingHead' => 'A real peds clinic, $25 a month.',
        'pricingBlurb' => 'Most pediatricians run the growth-chart module plus the basics.',
        'pricingLabel' => 'Solo pediatrician',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Growth charts module', '$5/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['QR patient card', '$4/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices (lite)', '$5/mo'],
        ],
        'pricingTotal' => 25,
        'testimonialsHead' => 'What pediatricians say.',
        'testimonials' => [
            ['Dr. Amara Okonkwo', 'Lagos, Nigeria', 'Parents love the weight-based dosing and the WhatsApp summary. I love that I no longer fight a spreadsheet.'],
            ['Dr. Mei-Lin Chen', 'Taipei, Taiwan', 'The vaccine reminders single-handedly raised our on-time rate from 64% to 91%. My nurses sleep better.'],
            ['Dr. Andrés Vega', 'Bogotá, Colombia', "My patients' parents are now genuinely invested in their child's growth chart. They show me at every visit."],
        ],
        'migrationBlurb' => 'Pediatric records live in immunization registries, EMRs, and growth-tracking apps. We pull them all into one timeline.',
        'migrateFrom' => ['Practo', 'eClinicalWorks', 'OfficePractic', 'Pediatric Practice Manager', 'Govt. immunization registry', 'Excel / CSV', 'Paper card'],
        'ctaTitle' => 'Run a peds clinic that grows with every child.',
        'ctaSub' => 'Start free. Turn on growth charts at the first well-visit.',
    ],

    'physio' => [
        'slug' => 'physiotherapists',
        'label' => 'Physiotherapists',
        'icon' => '🤸',
        'headline' => ['Programs your patients ', 'actually', ' follow.'],
        'heroBlurb' => 'Build exercise programs from a 600-video library and send them to your patient as a follow-along plan on WhatsApp. Track adherence and outcomes.',
        'heroProof' => ['490 physio clinics', '19 countries', 'From $17/mo'],
        'stats' => [['600+', 'Exercise videos'], ['+62%', 'Home-program adherence'], ['8', 'Outcome scales'], ['4.8', 'Avg physio rating']],
        'featsHead' => ['Tools for clinic-and-home physiotherapy.', 'Built for adherence, not paperwork.'],
        'feats' => [
            ['🎥', 'Exercise video library', '600+ HD videos, multiple angles, voice-over in 8 languages. Filter by region, condition, equipment.'],
            ['📅', 'Weekly program builder', 'Drag exercises into a 7-day grid. Sets, reps, hold time, rest — set once, sent everywhere.'],
            ['💬', 'Patient follow-along', "Patient sees the day's program on WhatsApp with a tap-to-play video. Check off as they go."],
            ['📊', 'Outcome scales', 'ODI, NDI, DASH, Roland-Morris, SF-36 — auto-scored, plotted over time.'],
            ['📈', 'Adherence tracking', "See who did Monday's exercises and who didn't. Auto-nudge skipped sessions."],
            ['📋', 'Pain & motion logs', 'VAS pain score and ROM measurements per visit, plotted alongside outcome scales.'],
        ],
        'workflowHead' => 'From first assessment to discharge.',
        'workflow' => [
            ['Assess & score', 'Run a baseline ODI/NDI. Record VAS, ROM. Photo or video your manual assessment.'],
            ['Build the program', 'Drag exercises from the library into a weekly grid. Set reps, hold, intensity.'],
            ['Send to patient', 'WhatsApp link. Patient opens it on the bus home — videos play, exercises check off.'],
            ['Track adherence', 'Daily and weekly view: who did what, who skipped, who reported pain.'],
            ['Reassess at week 4', 'Rerun the scales. Outcome plot side-by-side with adherence. Adjust the program.'],
        ],
        'pricingHead' => 'A real physio practice, $22 a month.',
        'pricingBlurb' => 'Solo physios run on Starter plus the exercise program module.',
        'pricingLabel' => 'Solo physiotherapist',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Exercise plans module', '$8/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 22,
        'testimonialsHead' => 'What physios say.',
        'testimonials' => [
            ['Dr. Maya Patel', 'Bristol, UK', "My patients actually do their home programs now. Adherence went from 30% to 78% in three months. That's the whole job."],
            ['Dr. Tomás Silva', 'São Paulo, Brazil', 'The Portuguese voice-over in the videos changed everything. My patients trust the program because they can hear instructions in their language.'],
            ['Dr. Hyun-woo Park', 'Seoul, South Korea', 'I run a sports physio clinic. The outcome scales plus video feedback let me discharge confidently.'],
        ],
        'migrationBlurb' => 'Physio records are messy — assessment PDFs, video files, paper programs. We import everything and re-link it by patient.',
        'migrateFrom' => ['Cliniko', 'PracticeHub', 'Jane App', 'Physitrack', 'TheraNest', 'Google Drive videos', 'Excel / CSV', 'Paper programs'],
        'ctaTitle' => 'Run a physio practice your patients stick with.',
        'ctaSub' => 'Start free. Turn on exercise plans when you write your first program.',
    ],
];
