<?php
// Specialty page data — ported from assets/js/specialty-data.jsx
// One entry per specialty slug. Used by gps.php, dentists.php, etc.

return [
    'dental' => [
        'slug' => 'dentists',
        'label' => 'Dentists',
        'icon' => '🦷',
        'heroV2' => [
            'badge' => 'Smart Software for Dental Clinics',
            'title' => 'Dental Clinic Management Software |',
            'titleAccent' => 'Complete Patient & Practice Management Solution',
            'tagline' => 'Simplify Your Dental Practice with',
            'body' => [
                'Manage patient charts, treatment plans, appointments, billing, and lab work from one secure platform built for dental clinics.',
                'eClinicPro helps you spend less time on admin and more time chairside — with tools tailored to how dentists actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional Dental Practice Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your Dental Clinic?',
            'sub' => 'Paper charts and spreadsheets slow down a busy dental practice and make recall and treatment tracking painful.',
            'challenges' => [
                ['Scattered Tooth Charts', 'Paper dental charts get lost, torn, or hard to read over years of visits.'],
                ['Low Recall Rates', 'Without automated reminders, cleaning and check-up recalls slip through the cracks.'],
                ['Treatment Plans Not Accepted', 'Confusing quotes on paper lower case acceptance and revenue.'],
                ['Lab Work Confusion', 'Tracking crowns, aligners and lab cases manually causes delays and re-dos.'],
                ['Billing & Insurance Errors', 'Manual billing and insurance codes lead to rejected claims and lost income.'],
                ['Implant Stock Chaos', 'No lot or expiry tracking for implants and materials means last-minute surprises.'],
            ],
            'solutions' => [
                ['records', 'Visual Dental Charts', 'FDI, Palmer or Universal charts stored securely per tooth.'],
                ['appointments', 'Automated Recall', 'Cleaning & check-up reminders that book themselves.'],
                ['billing', 'Treatment Quotes', 'Send clear, acceptable quotes on WhatsApp in seconds.'],
                ['inventory', 'Implant & Lab Tracking', 'Track implants by lot and lab cases end to end.'],
                ['reports', 'Reports & Analytics', 'See production, recall and acceptance at a glance.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Patient Smiles',
            'ctaTitleEnd' => ', Not Paperwork.',
            'ctaSub' => 'EClinicPro automates your dental clinic so you spend more time chairside and less on admin.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern Dental Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'Dental Software',
            'sub' => 'Everything you need to run a dental clinic efficiently and focus on what matters most – your patients.',
            'cards' => [
                ['icon' => 'patient', 'title' => 'Patient & Chart Management', 'items' => ['Complete digital patient records', 'Visual per-tooth dental charting', 'Medical & dental history tracking', 'Per-tooth imaging & X-rays', 'Secure cloud storage'], 'mock' => 'patient'],
                ['icon' => 'calendar', 'title' => 'Appointment & Recall Management', 'items' => ['Online and offline booking', 'Chair-wise scheduling', 'Recall by procedure (6-month, perio)', 'Automated SMS / WhatsApp reminders', 'Daily schedule overview'], 'mock' => 'calendar'],
                ['icon' => 'rx', 'title' => 'Treatment Plans & Prescriptions', 'items' => ['Multi-visit treatment plans', 'WhatsApp-ready quotes patients accept', 'Dental-specific Rx templates', 'Dose templates for antibiotics & analgesics'], 'mock' => 'rx'],
                ['icon' => 'billing', 'title' => 'Billing and Invoice Management', 'items' => ['Professional invoices per procedure', 'Track payments (paid & due)', 'Insurance-friendly billing', 'Download and email invoices'], 'mock' => 'billing'],
                ['icon' => 'medicine', 'title' => 'Implant & Material Inventory', 'items' => ['Implant tracking by lot number', 'Low stock alerts', 'Expiry date tracking', 'Consumables & material management'], 'mock' => 'medicine'],
                ['icon' => 'reports', 'title' => 'Reports and Analytics', 'items' => ['Daily production reports', 'Recall & acceptance reports', 'Revenue and billing reports', 'Chair utilization statistics', 'Export reports for analysis'], 'mock' => 'reports'],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => ['Manage multiple dental branches', 'Separate chair & doctor schedules per branch', 'Role-based access for staff', 'Cloud-based access from anywhere'],
                'branches' => [['Head Clinic', 'Ahmedabad', true], ['Branch Clinic', 'Surat', false], ['Branch Clinic', 'Rajkot', false]],
                'users' => [['Dr. Rakesh Mehta', 'Admin', 'admin'], ['Dr. Sneha Joshi', 'Dentist', 'doctor'], ['Kiran Shah', 'Hygienist', 'nurse'], ['Rohan Verma', 'Receptionist', 'reception']],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Charting. Better Care. Better Practice.',
            'title' => 'Benefits of Using Dental Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps dentists:',
            'items' => [
                ['time', 'Save Chairside Time', 'Chart in seconds and cut admin so you focus on treatment.'],
                ['paperwork', 'Reduce Paperwork', 'Go fully digital with charts, quotes and consent forms.'],
                ['experience', 'Improve Patient Experience', 'Clear quotes and easy booking build trust and acceptance.'],
                ['efficiency', 'Increase Chair Efficiency', 'Streamline scheduling and keep every chair productive.'],
                ['secure', 'Manage Records Securely', 'Store charts, images and history safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Track production, recall and acceptance with real data.'],
                ['followup', 'Improve Recall Management', 'Never miss a cleaning or follow-up with smart reminders.'],
                ['growth', 'Grow Your Practice Effectively', 'Higher recall and acceptance mean steady practice growth.'],
            ],
            'ctaTitle' => 'Smart Charting. Better Patient Care. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers dentists to run efficient clinics and deliver the best care to their patients.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your Dental Clinic',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your dental clinic operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Lost or Torn Charts', 'Paper dental charts get lost or become unreadable.'],
                ['appointments', 'Missed Recalls', 'No reminders means cleaning recalls are missed.'],
                ['rx', 'Rejected Treatment Plans', 'Confusing quotes lower case acceptance.'],
                ['billing', 'Billing & Claim Errors', 'Manual codes cause rejected insurance claims.'],
                ['medicine', 'Implant Stock Surprises', 'No lot or expiry tracking for implants and materials.'],
                ['reports', 'No Proper Reports', 'Production and recall reports take time and are inaccurate.'],
                ['clinic', 'Hard to Manage Multiple Chairs', 'Manual coordination across chairs and branches is difficult.'],
            ],
            'compareRows' => [
                ['records', 'Dental Charting'],
                ['appointments', 'Recall & Booking'],
                ['rx', 'Treatment Plans'],
                ['billing', 'Billing & Insurance'],
                ['medicine', 'Implant & Material Tracking'],
                ['reports', 'Production Reports'],
                ['clinic', 'Multi-Chair Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient dental practice management.',
            'digitalItems' => [
                'Visual, secure, and easy-to-access dental charts.',
                'Automated recall reminders that book themselves.',
                'Clear treatment quotes patients accept on WhatsApp.',
                'Insurance-friendly invoices and payment tracking.',
                'Implant and material tracking by lot and expiry.',
                'Lab case tracking from impression to fit.',
                'Instant production, recall and acceptance reports.',
                'Seamless multi-chair and multi-branch management.',
            ],
            'ctaTitle' => 'Save Time. Raise Acceptance. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart dental practice management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro Dental Clinic Management Software.',
            'items' => [
                ['software', 'What is Dental Clinic Management Software?', 'It is a digital solution that helps dentists manage charts, appointments, treatment plans, prescriptions, billing, lab work, inventory and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for single-chair clinics?', 'Yes. EClinicPro works for solo dentists as well as large multi-chair, multi-branch dental groups.'],
                ['history', 'Can I chart per tooth and store X-rays?', 'Yes. EClinicPro supports FDI, Palmer and Universal charting with per-tooth imaging, X-rays and full history.'],
                ['billing', 'Does EClinicPro support billing and insurance?', 'Yes. The software provides per-procedure billing, payment tracking, insurance-friendly invoices and financial reporting.'],
                ['cloud', 'Is EClinicPro cloud-based?', 'Yes. You can access your dental clinic data securely from anywhere, anytime.'],
            ],
        ],
        'headline' => ['A clinic OS that thinks in ', 'teeth', ', not in spreadsheets.'],
        'heroBlurb' => 'Visual charting, treatment plans your patients understand, and recall that runs itself. Built with dentists in 14 countries.',
        'heroProof' => ['412 dental clinics', '14 countries', 'From $13/mo'],
        'stats' => [['+71%', 'Recall rate vs paper'], ['+30%', 'Treatment-plan acceptance'], ['−42%', 'Time charting per patient'], ['4.9', 'Avg dentist rating']],
        'featsHead' => ['Six things every dental clinic needs.', "None of the stuff you don't."],
        'feats' => [
            ['🦷', 'Visual dental chart', 'FDI, Palmer, or Universal numbering. Tap a tooth — see every note, image, and procedure since the first visit.'],
            ['🖼️', 'Per-tooth imaging', 'X-rays, intraoral photos, scans — attach to a tooth, a quadrant, or the whole arch. Drag, drop, done.'],
            ['🧾', 'Treatment plans + quotes', 'Plan a course of work, send a quote your patient can accept on WhatsApp, track each visit against it.'],
            ['📅', 'Recall by procedure', '6-month cleanings, 3-month perio, annual whitening — auto-scheduled reminders that book themselves.'],
            ['℞', 'Dental-specific Rx', 'Antibiotics, analgesics, fluoride — pre-loaded with dose templates dental colleges actually use.'],
            ['💊', 'Implant & material inventory', 'Track every implant by lot. Expiry alerts before the next big patient lands in your chair.'],
        ],
        'workflowHead' => 'From check-in to recall, in five steps.',
        'workflow' => [
            ['Patient arrives', 'Receptionist scans the QR card. Chart loads with last visit, allergies, payment status.'],
            ['You chart in the chair', 'Open the dental chart on iPad. Tap tooth 16, mark a caries class II, attach a photo — 20 seconds.'],
            ['Build the plan', 'Drag procedures into a multi-visit treatment plan with materials and time blocks.'],
            ['Quote sent on WhatsApp', 'Patient gets a clean PDF with line items, total, and an "Accept & book" link. No printer.'],
            ['Recall, automated', 'Six months later, the system books them in for cleaning and sends the reminder.'],
        ],
        'pricingHead' => 'A real dental clinic, $33 a month.',
        'pricingBlurb' => "Most single-chair dentists run on Starter plus a few targeted modules. Here's a real configuration.",
        'pricingLabel' => 'Single-chair dental clinic',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Dental charting module', '$9/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Billing & invoices', '$9/mo'],
            ['Analytics', '$9/mo'],
        ],
        'pricingTotal' => 33,
        'testimonialsHead' => 'What dentists say.',
        'testimonials' => [
            ['Dr. James Whitfield', 'Toronto, Canada', 'I ran paper-and-Excel chairside for 14 years. We switched in a long weekend and our recall rate went from 38% to 71% in the first quarter.'],
            ['Dr. Ananya Rao', 'Bangalore, India', 'The treatment plan PDF is so clean my patients actually read it. Case acceptance up 30%.'],
            ['Dr. Yusuf El-Sayed', 'Dubai, UAE', 'Multilingual quotes in English and Arabic with the right insurance codes. Nothing else does this for under $100/month.'],
        ],
        'migrationBlurb' => 'If you have over 500 records, our team handles migration end-to-end. We import from any of the systems below — and most spreadsheets.',
        'migrateFrom' => ['Dentrix', 'Eaglesoft', 'Open Dental', 'Curve', 'Practo', 'Cliniko', 'Drchrono', 'SimplePractice', 'Excel / CSV', 'Paper register'],
        'ctaTitle' => 'Run a dental clinic that thinks in teeth.',
        'ctaSub' => "Start free. Add the dental module when you're ready.",
    ],

    'gp' => [
        'slug' => 'gps',
        'label' => 'GPs',
        'icon' => '🩺',
        'heroV2' => [
            'badge' => 'Smart Software for GP & OPD Clinics',
            'title' => 'GP Clinic Management Software |',
            'titleAccent' => 'Complete Patient & OPD Management Solution',
            'tagline' => 'Simplify Your GP Practice with',
            'body' => [
                'Manage walk-ins, triage, vitals, prescriptions, billing and follow-ups from one secure platform built for busy OPD clinics.',
                'eClinicPro helps you see more patients with less friction — with tools tailored to how general practitioners actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional OPD Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your GP Clinic?',
            'sub' => 'A busy general practice on paper means long queues, missed vitals and follow-ups that never happen.',
            'challenges' => [
                ['Long Waiting Queues', 'Manual walk-in handling creates chaos and long patient waits.'],
                ['Vitals on Loose Paper', 'BP, weight and temperature notes get lost before they reach the doctor.'],
                ['Repetitive Prescriptions', 'Writing the same common scripts by hand wastes valuable OPD time.'],
                ['Missed Chronic Follow-ups', 'HTN and diabetes reviews are hard to track manually.'],
                ['Billing Errors', 'Manual billing at a busy front desk causes mistakes and disputes.'],
                ['No Visit Summaries', 'Patients leave without a clear record of advice and medicines.'],
            ],
            'solutions' => [
                ['records', 'Fast Patient Records', 'Pull up history, allergies and last visit in seconds.'],
                ['appointments', 'Walk-in Triage & Queue', 'Live queue with severity so everyone knows the wait.'],
                ['billing', 'Quick Billing', 'Bill and reconcile OPD visits in a couple of taps.'],
                ['inventory', 'Chronic Care Tracking', 'Timelines for HTN, diabetes and COPD with overdue alerts.'],
                ['reports', 'Reports & Analytics', 'See OPD load, revenue and repeat visits at a glance.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Patient Care',
            'ctaTitleEnd' => ', Not the Front Desk.',
            'ctaSub' => 'EClinicPro automates your OPD so you spend more time treating and less time managing queues.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern GP Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'GP Software',
            'sub' => 'Everything you need to run a busy OPD efficiently and focus on what matters most – your patients.',
            'cards' => [
                ['icon' => 'patient', 'title' => 'Patient Management', 'items' => ['Complete digital patient records', 'Allergy & chronic condition flags', 'Medical history tracking', 'Appointment & visit history', 'Secure cloud storage'], 'mock' => 'patient'],
                ['icon' => 'calendar', 'title' => 'Walk-in & Appointment Management', 'items' => ['5-second walk-in triage', 'Live queue with wait estimates', 'Online and offline booking', 'Automated SMS / WhatsApp reminders', 'Daily schedule overview'], 'mock' => 'calendar'],
                ['icon' => 'rx', 'title' => 'Prescription Management', 'items' => ['Top-200 condition Rx templates', 'One-tap sign and print', 'Save frequently used medicines', 'Dose templates for common drugs'], 'mock' => 'rx'],
                ['icon' => 'billing', 'title' => 'Billing and Invoice Management', 'items' => ['Fast OPD billing', 'Track payments (paid & due)', 'GST-compatible invoices', 'Download and email invoices'], 'mock' => 'billing'],
                ['icon' => 'medicine', 'title' => 'Vitals & Chronic Care', 'items' => ['Vitals capture on tablet', 'Out-of-range red flags', 'Chronic care timelines (HTN, diabetes)', 'Overdue check reminders'], 'mock' => 'medicine'],
                ['icon' => 'reports', 'title' => 'Reports and Analytics', 'items' => ['Daily OPD reports', 'Doctor performance reports', 'Revenue and billing reports', 'Repeat-visit statistics', 'Export reports for analysis'], 'mock' => 'reports'],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => ['Manage multiple OPD branches', 'Separate doctor & queue per branch', 'Role-based access for staff', 'Cloud-based access from anywhere'],
                'branches' => [['Head Clinic', 'Ahmedabad', true], ['Branch Clinic', 'Surat', false], ['Branch Clinic', 'Rajkot', false]],
                'users' => [['Dr. Aarav Sharma', 'Admin', 'admin'], ['Dr. Meera Nair', 'GP', 'doctor'], ['Anita Shah', 'Nurse', 'nurse'], ['Rohan Verma', 'Receptionist', 'reception']],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Flow. Better Care. Better Practice.',
            'title' => 'Benefits of Using GP Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps general practitioners:',
            'items' => [
                ['time', 'Save Administrative Time', 'Automate triage, vitals and billing to see more patients.'],
                ['paperwork', 'Reduce Paperwork', 'Go digital and eliminate loose notes and paper files.'],
                ['experience', 'Improve Patient Experience', 'Shorter waits, clear summaries and easy booking.'],
                ['efficiency', 'Increase OPD Efficiency', 'Streamline the whole visit from walk-in to summary.'],
                ['secure', 'Manage Records Securely', 'Store patient data safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Get insights on OPD load and revenue to decide better.'],
                ['followup', 'Improve Follow-up Management', 'Never miss a chronic review with smart reminders.'],
                ['growth', 'Grow Your Practice Effectively', 'Smoother visits and follow-ups bring patients back.'],
            ],
            'ctaTitle' => 'Smart OPD Management. Better Patient Care. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers general practitioners to run efficient clinics and deliver the best care.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your OPD',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your OPD operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Lost Patient Files', 'Paper files are slow to find and easy to misplace.'],
                ['appointments', 'Chaotic Queues', 'No live queue means long, unpredictable waits.'],
                ['rx', 'Repetitive Prescriptions', 'Writing common scripts by hand wastes time.'],
                ['billing', 'Front-desk Billing Errors', 'Manual billing at a busy desk causes disputes.'],
                ['medicine', 'Vitals Lost on Paper', 'Vitals notes get lost before reaching the doctor.'],
                ['reports', 'No Proper Reports', 'OPD load and revenue reports are slow and inaccurate.'],
                ['clinic', 'Hard to Manage Branches', 'Coordinating multiple OPDs manually is difficult.'],
            ],
            'compareRows' => [
                ['records', 'Patient Records'],
                ['appointments', 'Walk-in & Queue'],
                ['rx', 'Prescriptions'],
                ['billing', 'OPD Billing'],
                ['medicine', 'Vitals & Chronic Care'],
                ['reports', 'Daily Reports'],
                ['clinic', 'Multi-Clinic Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient OPD management.',
            'digitalItems' => [
                'Digital, secure, and easy-to-access patient records.',
                'Live walk-in queue with real-time wait estimates.',
                'One-tap prescriptions from top-200 templates.',
                'Fast OPD billing and payment tracking.',
                'Vitals captured on tablet with red-flag alerts.',
                'Chronic care timelines with overdue reminders.',
                'Instant daily, weekly, and monthly reports.',
                'Seamless multi-clinic and user management.',
            ],
            'ctaTitle' => 'Save Time. Cut Queues. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart OPD management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro GP Clinic Management Software.',
            'items' => [
                ['software', 'What is GP Clinic Management Software?', 'It is a digital solution that helps general practitioners manage walk-ins, triage, vitals, prescriptions, billing, follow-ups and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for solo GPs?', 'Yes. EClinicPro works for solo GPs as well as large multi-doctor, multi-branch OPD clinics.'],
                ['history', 'Can I manage chronic patients digitally?', 'Yes. EClinicPro provides chronic care timelines for HTN, diabetes and COPD with target bands and overdue alerts.'],
                ['billing', 'Does EClinicPro support billing and invoices?', 'Yes. The software provides fast OPD billing, payment tracking, GST-compatible invoices and financial reporting.'],
                ['cloud', 'Is EClinicPro cloud-based?', 'Yes. You can access your clinic data securely from anywhere, anytime.'],
            ],
        ],
        'headline' => ['For the everyday doctor, ', 'finally', ' given great tools.'],
        'heroBlurb' => 'OPD-ready out of the box. Triage, vitals, common Rx templates, and a fast walk-in flow — the GP basics, beautifully.',
        'heroProof' => ['1,420 GP clinics', '32 countries', 'From $15/mo'],
        'stats' => [['8 min', 'Avg wait time saved'], ['−55%', 'Time at front desk'], ['+22%', 'Repeat visit rate'], ['4.8', 'Avg GP rating']],
        'featsHead' => ['Built for the rhythm of a busy OPD.', 'Triage, treat, recall.'],
        'feats' => [
            ['⚡', 'Walk-in triage', 'Add a walk-in in 5 seconds with severity. The queue updates everyone in real time.'],
            ['📈', 'Vitals on entry', "Nurse captures vitals on a tablet. They're on your screen by the time the patient sits down."],
            ['℞', 'Top-200 Rx templates', 'Pre-built scripts for the top 200 conditions. Sign with one tap, edit when needed.'],
            ['📋', 'Chronic care timelines', 'HTN, diabetes, COPD — one timeline view with target bands and overdue checks.'],
            ['👨‍👩‍👧', 'Family history', 'A clean visual family tree with hereditary tagging. Builds itself from each visit.'],
            ['💬', 'Post-visit summary', 'Patients get a clean summary on WhatsApp before they get to the car park.'],
        ],
        'workflowHead' => 'A 10-minute OPD visit, end to end.',
        'workflow' => [
            ['Walk-in or arrives', 'Receptionist tags severity. Patient enters queue with a live wait estimate.'],
            ['Vitals captured', 'Nurse records BP, HR, weight on tablet. Flagged in red if outside the target band.'],
            ['Doctor reviews', 'You see vitals, last visit, allergies and the suggested Rx template all on one screen.'],
            ['Rx + visit notes', 'One tap to sign Rx. Voice-dictate visit notes or type in SOAP.'],
            ['Summary delivered', 'WhatsApp summary, follow-up booked, billing reconciled before they leave.'],
        ],
        'pricingHead' => 'A real solo GP, $24 a month.',
        'pricingBlurb' => "Most solo GPs run on Starter plus the essentials. Pay nothing for the chronic-care features you don't use yet.",
        'pricingLabel' => 'Solo GP, ~25 patients/day',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Digital prescriptions', '$6/mo'],
            ['QR patient card', '$4/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 24,
        'testimonialsHead' => 'What GPs say.',
        'testimonials' => [
            ['Dr. Aarav Sharma', 'Mumbai, India', 'I switched from paper in two weekends. The QR cards alone cut my check-in time by 80%. My nurses cried with joy.'],
            ['Dr. Ben Carter', 'Bristol, UK', 'Calm, fast, no junk. It feels like a tool made for clinicians, not for the people selling to clinicians.'],
            ['Dr. Liang Wei', 'Singapore', 'I see 40 patients a day. The vitals trend chart catches things I would have missed flipping through paper.'],
        ],
        'migrationBlurb' => 'Coming from EMRs, paper, or a tangle of spreadsheets — we move it all. Most clinics are live in under a week.',
        'migrateFrom' => ['Practo', 'Drchrono', 'Athenahealth', 'eClinicalWorks', 'EMIS', 'SystmOne', 'Cliniko', 'SimplePractice', 'Excel / CSV', 'Paper register'],
        'ctaTitle' => 'Run a GP practice that respects your time.',
        'ctaSub' => 'Start free. Add modules when your day demands it.',
    ],

    'homeopathy' => [
        'slug' => 'homeopathy-clinic-management-software',
        'label' => 'Homeopaths',
        'icon' => '🌿',
        'heroImage' => '/assets/img/Smart-Software-for-Homeopathy-Clinics-bg.png',
        'headline' => ['Built for ', 'case taking', ', not just clicking.'],
        'heroV2' => [
            'badge' => 'Smart Software for Homeopathy Clinics',
            'title' => 'Homeopathy Clinic Management Software |',
            'titleAccent' => 'Complete Patient & Clinic Management Solution',
            'tagline' => 'Simplify Your Homeopathy Practice with',
            'body' => [
                'Manage patient records, appointments, prescriptions, billing, and clinic operations from one secure platform built for homeopathy practices.',
                'eClinicPro helps you spend less time on admin and more time with patients — with tools tailored to how homeopaths actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional Clinic Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your Homeopathy Clinic?',
            'sub' => 'Traditional paper-based clinic management can slow down your practice and create unnecessary challenges.',
            'challenges' => [
                ['Lost Patient Records', 'Important patient information can be misplaced or lost.'],
                ['Missed Appointments', 'Manual scheduling leads to missed or double bookings.'],
                ['Billing Errors', 'Manual billing increases the risk of calculation mistakes.'],
                ['Difficulty Tracking Medicine Inventory', 'Hard to maintain accurate stock levels and availability.'],
                ['Time-consuming Manual Reports', 'Creating reports manually takes time and effort.'],
                ['Challenges Managing Follow-up Visits', 'Tracking follow-ups manually can lead to missed visits.'],
            ],
            'solutions' => [
                ['records', 'Patient Records', 'Store & access patient data securely.'],
                ['appointments', 'Smart Appointments', 'Schedule & manage appointments easily.'],
                ['billing', 'Billing Automation', 'Generate invoices & manage payments.'],
                ['inventory', 'Medicine Inventory', 'Track stock levels & manage medicines.'],
                ['followup', 'Follow-up Reminders', 'Never miss a follow-up or patient check-in.'],
                ['reports', 'Reports & Analytics', 'Get insights & make better decisions.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Patient Care',
            'ctaTitleEnd' => ', Not Paperwork.',
            'ctaSub' => 'EClinicPro automates your entire clinic so you spend more time with patients.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern Homeopathy Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'Homeopathy Software',
            'sub' => 'Everything you need to manage your homeopathy clinic efficiently and focus on what matters most – your patients.',
            'cards' => [
                [
                    'icon' => 'patient',
                    'title' => 'Patient Management',
                    'items' => [
                        'Complete digital patient records',
                        'Follow-up reminders',
                        'Medical history tracking',
                        'Appointment history',
                        'Secure cloud storage',
                    ],
                    'mock' => 'patient',
                ],
                [
                    'icon' => 'calendar',
                    'title' => 'Appointment Management',
                    'items' => [
                        'Online and offline appointment booking',
                        'Queue management',
                        'Appointment calendar',
                        'Automated SMS / email reminders',
                        'Daily schedule overview',
                    ],
                    'mock' => 'calendar',
                ],
                [
                    'icon' => 'rx',
                    'title' => 'Homeopathy Prescription Management',
                    'items' => [
                        'Create and manage prescriptions digitally',
                        'Print and share prescriptions easily',
                        'Save frequently used medicines',
                        'Potency and dosage management',
                    ],
                    'mock' => 'rx',
                ],
                [
                    'icon' => 'billing',
                    'title' => 'Billing and Invoice Management',
                    'items' => [
                        'Generate professional invoices',
                        'Track payments (paid & due)',
                        'GST-compatible billing support',
                        'Download and email invoices',
                    ],
                    'mock' => 'billing',
                ],
                [
                    'icon' => 'medicine',
                    'title' => 'Medicine and Inventory Management',
                    'items' => [
                        'Medicine stock management',
                        'Low stock alerts',
                        'Expiry date tracking',
                        'Batch and potency tracking',
                    ],
                    'mock' => 'medicine',
                ],
                [
                    'icon' => 'reports',
                    'title' => 'Reports and Analytics',
                    'items' => [
                        'Daily patient reports',
                        'Doctor performance reports',
                        'Revenue and billing reports',
                        'Appointment statistics',
                        'Export reports for analysis',
                    ],
                    'mock' => 'reports',
                ],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => [
                    'Manage multiple branches',
                    'Separate doctor & patient database per branch',
                    'Role-based access for staff',
                    'Cloud-based access from anywhere',
                ],
                'branches' => [
                    ['Head Clinic', 'Ahmedabad', true],
                    ['Branch Clinic', 'Surat', false],
                    ['Branch Clinic', 'Rajkot', false],
                ],
                'users' => [
                    ['Dr. Hitesh Sharma', 'Admin', 'admin'],
                    ['Dr. Priya Patel', 'Doctor', 'doctor'],
                    ['Anita Shah', 'Nurse', 'nurse'],
                    ['Rohan Verma', 'Receptionist', 'reception'],
                ],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Management. Better Care. Better Practice.',
            'title' => 'Benefits of Using Homeopathy Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps homeopathy doctors:',
            'items' => [
                ['time', 'Save Administrative Time', 'Automate routine tasks and focus more on patient care.'],
                ['paperwork', 'Reduce Paperwork', 'Go digital and eliminate manual paperwork.'],
                ['experience', 'Improve Patient Experience', 'Faster service, easy booking and better communication.'],
                ['efficiency', 'Increase Clinic Efficiency', 'Streamline operations and boost productivity.'],
                ['secure', 'Manage Records Securely', 'Store and access patient data safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Get detailed insights to make better decisions.'],
                ['followup', 'Improve Follow-up Management', 'Never miss a follow-up with smart reminders.'],
                ['growth', 'Grow Your Practice Effectively', 'Better management leads to more patients and growth.'],
            ],
            'ctaTitle' => 'Smart Clinic Management. Better Patient Care. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers homeopathy doctors to manage their clinics efficiently and deliver the best care to their patients.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your Clinic',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your homeopathy clinic operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Lost or Misplaced Records', 'Paper files can be lost or damaged.'],
                ['appointments', 'Missed Appointments', 'No reminders, leads to missed visits.'],
                ['rx', 'Prescription Errors', 'Handwritten prescriptions can have mistakes.'],
                ['billing', 'Billing Mistakes', 'Manual calculations cause billing and stock errors.'],
                ['medicine', 'Stock Mismanagement', 'No proper tracking of medicines, expiry or stock.'],
                ['followup', 'Follow-ups Missed', 'Difficult to remember follow-up visits.'],
                ['reports', 'No Proper Reports', 'Reports take time and are not accurate.'],
                ['clinic', 'Hard to Manage Multiple Clinics', 'Manual coordination is difficult and inefficient.'],
            ],
            'compareRows' => [
                ['records', 'Patient Records'],
                ['appointments', 'Appointment Booking'],
                ['rx', 'Prescription History'],
                ['billing', 'Billing & Invoices'],
                ['medicine', 'Medicine Management'],
                ['followup', 'Follow-Up Tracking'],
                ['reports', 'Daily Reports'],
                ['clinic', 'Multi-Clinic Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient clinic management.',
            'digitalItems' => [
                'Digital, secure, and easy-to-access patient records.',
                'Smart reminders for appointments.',
                'Instant prescription creation and access.',
                'Professional invoice generation and payment tracking.',
                'Real-time medicine stock and expiry tracking.',
                'Automated follow-up reminders.',
                'Instant daily, weekly, and monthly reports.',
                'Seamless multi-clinic and user management.',
            ],
            'ctaTitle' => 'Save Time. Reduce Errors. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart clinic management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro Homeopathy Clinic Management Software.',
            'items' => [
                ['software', 'What is Homeopathy Clinic Management Software?', 'Homeopathy Clinic Management Software is a digital solution that helps doctors manage appointments, patient records, prescriptions, billing, inventory, and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for small clinics?', 'Yes. EClinicPro is designed for both individual practitioners and large multi-clinic organizations.'],
                ['history', 'Can I manage patient history digitally?', 'Yes. EClinicPro stores complete patient history, prescriptions, visits, and treatment records securely.'],
                ['billing', 'Does EClinicPro support billing and invoices?', 'Yes. The software provides billing, payment tracking, invoice generation, and financial reporting.'],
                ['cloud', 'Is EClinicPro cloud-based?', 'Yes. You can access your clinic data securely from anywhere.'],
            ],
        ],
        'heroBlurb' => 'Long-form repertory notes, a 3,200-remedy database, potency picker, and antidote warnings. The first software a homeopath might actually love.',
        'heroProof' => ['620 homeo clinics', '11 countries', 'From $13/mo'],
        'stats' => [['3,200', 'Remedies in database'], ['15 min', 'Saved per case'], ['6 mo', 'Follow-up tracking'], ['4.9', 'Avg homeopath rating']],
        'featsHead' => ['A clinic OS that speaks homeopathy.', 'Not a generic record system in disguise.'],
        'feats' => [
            ['🧫', 'Remedy database', '3,200 remedies with potency, antidotes, miasm tags and Materia Medica references. Searchable in seconds.'],
            ['📋', 'Repertory case taking', 'A real long-form template — mental generals, physical generals, particulars, modalities — built in.'],
            ['⚡', 'Potency picker', '6X to 1M with a sliding scale. Notes on prescribed potency travel with the case.'],
            ['🛡️', 'Antidote engine', 'Coffee, camphor, peppermint — the system warns when antidotes appear in another part of the chart.'],
            ['📅', 'Follow-up scheduler', 'Three weeks, six weeks, three months — your follow-up cadence built into the calendar.'],
            ['📈', 'Case history view', 'Every remedy ever given, every reaction, every modality change — in one scrollable timeline.'],
        ],
        'workflowHead' => 'From first interview to long-term follow-up.',
        'workflow' => [
            ['First interview', 'Long-form template loads. You take a 60-minute case with mental, physical, particular sections.'],
            ['Repertorize', 'Pick rubrics from the case. The remedy DB suggests top matches with confidence scoring.'],
            ['Prescribe', 'Select remedy, potency, schedule. Antidote warnings surface if anything conflicts.'],
            ['Follow-up books itself', 'System schedules 3-week and 6-week follow-ups, sends WhatsApp reminders.'],
            ['Track over months', 'Every change rolled into a timeline. You see the case story at a glance.'],
        ],
        'pricingHead' => 'A real homeopath, $22 a month.',
        'pricingBlurb' => 'Most solo homeopaths run on Starter plus the remedy database. The rest is free.',
        'pricingLabel' => 'Solo homeopath',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Remedy database', '$7/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 22,
        'testimonialsHead' => 'What homeopaths say.',
        'testimonials' => [
            ['Dr. Priya Iyer', 'Pune, India', 'Finally, software that knows what a repertory case-taking sheet looks like. The remedy DB is shockingly thorough.'],
            ['Dr. Elena Costa', 'Lisbon, Portugal', 'The antidote warnings have saved me three times in the first month. Worth the cost a hundred times over.'],
            ['Dr. Rohit Kapoor', 'Delhi, India', "Long-form case notes that don't fight me. I take cases the way I was taught, not the way the software demands."],
        ],
        'migrationBlurb' => 'Most homeopaths come from paper case books or Word documents. We OCR your old cases and import them, attribute by attribute.',
        'migrateFrom' => ['Paper case books', 'Word / PDF cases', 'Practo', 'Cliniko', 'HomeoSoft', 'Excel / CSV', 'RADAR exports'],
        'ctaTitle' => 'Run a homeo practice that respects the case.',
        'ctaSub' => 'Start free. Turn on the remedy DB when you take your first case.',
    ],

    'derma' => [
        'slug' => 'dermatologists',
        'label' => 'Dermatologists',
        'icon' => '✨',
        'heroV2' => [
            'badge' => 'Smart Software for Dermatology Clinics',
            'title' => 'Dermatology Clinic Management Software |',
            'titleAccent' => 'Complete Patient & Skin-Care Management Solution',
            'tagline' => 'Simplify Your Dermatology Practice with',
            'body' => [
                'Manage body-map photos, treatment plans, appointments, billing and follow-ups from one secure platform built for skin clinics.',
                'eClinicPro helps you show real progress and spend less time on admin — with tools tailored to how dermatologists actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional Dermatology Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your Dermatology Clinic?',
            'sub' => 'Skin care is visual, but paper records and scattered photos make it impossible to show progress clearly.',
            'challenges' => [
                ['Scattered Skin Photos', 'Before/after images live across phones, drives and folders.'],
                ['No Progress Comparison', 'Hard to place two visits side by side to prove results.'],
                ['Inconsistent Lesion Records', 'Manual measurements make lesion tracking unreliable.'],
                ['Complex Treatment Plans', 'Topical and systemic sequences are hard to track on paper.'],
                ['Prescription Risks', 'Retinoid and biologic warnings get missed without prompts.'],
                ['Low Patient Retention', 'Patients drop off when they can\'t see their improvement.'],
            ],
            'solutions' => [
                ['records', 'Body-Map Photo Logging', 'Photos auto-organized by body area and date.'],
                ['appointments', 'Smart Appointments', 'Schedule visits, procedures and reviews easily.'],
                ['billing', 'Billing Automation', 'Invoice procedures and track payments with ease.'],
                ['inventory', 'Treatment Plan Tracking', 'Sequenced topical & systemic plans with reminders.'],
                ['reports', 'Reports & Analytics', 'Track retention, procedures and revenue clearly.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Skin Results',
            'ctaTitleEnd' => ', Not Paperwork.',
            'ctaSub' => 'EClinicPro automates your skin clinic so you spend more time on care and results.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern Dermatology Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'Dermatology Software',
            'sub' => 'Everything you need to run a skin clinic efficiently and focus on what matters most – your patients.',
            'cards' => [
                ['icon' => 'patient', 'title' => 'Patient & Photo Management', 'items' => ['Complete digital patient records', 'Body-map photo logging by zone', 'Side-by-side visit comparison', 'Skin & allergy history tracking', 'Secure cloud storage'], 'mock' => 'patient'],
                ['icon' => 'calendar', 'title' => 'Appointment Management', 'items' => ['Online and offline booking', 'Procedure room scheduling', 'Follow-up photo reminders', 'Automated SMS / WhatsApp reminders', 'Daily schedule overview'], 'mock' => 'calendar'],
                ['icon' => 'rx', 'title' => 'Treatment Plans & Prescriptions', 'items' => ['Sequenced topical & systemic plans', 'Derma-aware Rx with potency ladder', 'Retinoid pregnancy warnings', 'Save frequently used regimens'], 'mock' => 'rx'],
                ['icon' => 'billing', 'title' => 'Billing and Invoice Management', 'items' => ['Professional procedure invoices', 'Track payments (paid & due)', 'Package & session billing', 'Download and email invoices'], 'mock' => 'billing'],
                ['icon' => 'medicine', 'title' => 'Lesion & Imaging Tools', 'items' => ['Lesion measurement (ABCD)', 'Per-zone image timelines', 'Slide-to-compare imaging', 'Product & consumable tracking'], 'mock' => 'medicine'],
                ['icon' => 'reports', 'title' => 'Reports and Analytics', 'items' => ['Daily patient reports', 'Retention & outcome reports', 'Revenue and billing reports', 'Procedure statistics', 'Export reports for analysis'], 'mock' => 'reports'],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => ['Manage multiple skin clinics', 'Separate doctor & procedure rooms per branch', 'Role-based access for staff', 'Cloud-based access from anywhere'],
                'branches' => [['Head Clinic', 'Ahmedabad', true], ['Branch Clinic', 'Surat', false], ['Branch Clinic', 'Rajkot', false]],
                'users' => [['Dr. Sofia Marin', 'Admin', 'admin'], ['Dr. Kavya Reddy', 'Dermatologist', 'doctor'], ['Anita Shah', 'Therapist', 'nurse'], ['Rohan Verma', 'Receptionist', 'reception']],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Imaging. Better Care. Better Practice.',
            'title' => 'Benefits of Using Dermatology Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps dermatologists:',
            'items' => [
                ['time', 'Save Administrative Time', 'Automate photo admin and paperwork to focus on skin.'],
                ['paperwork', 'Reduce Paperwork', 'Go digital with photos, plans and consent forms.'],
                ['experience', 'Improve Patient Experience', 'Show clear before/after progress that builds trust.'],
                ['efficiency', 'Increase Clinic Efficiency', 'Streamline procedures, imaging and follow-ups.'],
                ['secure', 'Manage Records Securely', 'Store sensitive photos and data safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Track retention, outcomes and revenue with real data.'],
                ['followup', 'Improve Follow-up Management', 'Never miss a review or photo follow-up.'],
                ['growth', 'Grow Your Practice Effectively', 'Visible results keep patients on the full course.'],
            ],
            'ctaTitle' => 'Smart Imaging. Better Patient Care. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers dermatologists to run efficient clinics and prove real results.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your Skin Clinic',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your dermatology clinic operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Scattered Photos', 'Skin images spread across phones and drives.'],
                ['appointments', 'Missed Reviews', 'No reminders means skipped follow-up photos.'],
                ['rx', 'Prescription Risks', 'Retinoid and biologic warnings get missed.'],
                ['billing', 'Billing Mistakes', 'Manual package and session billing causes errors.'],
                ['medicine', 'Unreliable Lesion Tracking', 'Hand measurements make progress hard to prove.'],
                ['reports', 'No Proper Reports', 'Retention and outcome reports are slow and inaccurate.'],
                ['clinic', 'Hard to Manage Branches', 'Coordinating rooms and branches manually is difficult.'],
            ],
            'compareRows' => [
                ['records', 'Skin Photo Records'],
                ['appointments', 'Appointment Booking'],
                ['rx', 'Treatment Plans'],
                ['billing', 'Procedure Billing'],
                ['medicine', 'Lesion & Imaging Tools'],
                ['reports', 'Outcome Reports'],
                ['clinic', 'Multi-Clinic Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient dermatology management.',
            'digitalItems' => [
                'Body-map photos organized by zone and date.',
                'Side-by-side comparison to prove progress.',
                'Sequenced treatment plans with reminders.',
                'Procedure and package billing with tracking.',
                'Lesion measurement with ABCD criteria.',
                'Derma-aware prescriptions with safety warnings.',
                'Instant retention, outcome and revenue reports.',
                'Seamless multi-clinic and user management.',
            ],
            'ctaTitle' => 'Save Time. Show Results. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart dermatology management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro Dermatology Clinic Management Software.',
            'items' => [
                ['software', 'What is Dermatology Clinic Management Software?', 'It is a digital solution that helps dermatologists manage skin photos, treatment plans, appointments, prescriptions, billing and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for small skin clinics?', 'Yes. EClinicPro works for solo dermatologists as well as large multi-branch skin and aesthetic clinics.'],
                ['history', 'Can I track before/after photos digitally?', 'Yes. EClinicPro logs photos on a body-map by zone and date with side-by-side comparison and lesion measurement.'],
                ['billing', 'Does EClinicPro support procedure and package billing?', 'Yes. The software provides procedure, session and package billing with payment tracking and reporting.'],
                ['cloud', 'Is EClinicPro cloud-based and secure?', 'Yes. Your sensitive skin photos and patient data are stored securely and accessible from anywhere.'],
            ],
        ],
        'headline' => ['Before, after, and ', 'everything', ' in between.'],
        'heroBlurb' => 'Photo timelines per body area, side-by-side compare, and lesion measurement — built for skin, not bent into it.',
        'heroProof' => ['380 derma clinics', '18 countries', 'From $20/mo'],
        'stats' => [['+44%', 'Patient retention'], ['−60%', 'Photo admin time'], ['3D', 'Body-map zones'], ['4.9', 'Avg derma rating']],
        'featsHead' => ['The visual tools dermatology needs.', 'Nothing more, nothing less.'],
        'feats' => [
            ['🖼️', 'Body-map photo logging', 'Tap a body region, attach photos. They organize themselves by area and date forever.'],
            ['🔍', 'Side-by-side compare', 'Pull any two visits next to each other. Slide to wipe between. Patients see progress in 5 seconds.'],
            ['📐', 'Lesion measurement', 'Draw a contour, get area, diameter, asymmetry. Track all four ABCD criteria per lesion.'],
            ['🥗', 'Topical & systemic plans', 'Sequenced treatment plans with photos at each phase. Auto-reminders for application steps.'],
            ['℞', 'Derma-aware Rx', 'Steroid potency ladder, biologics scheduling, retinoid pregnancy warnings built into the workflow.'],
        ],
        'workflowHead' => 'From first photo to twelve-month outcome.',
        'workflow' => [
            ['New patient, body map', 'Tap the regions of concern. Attach phone photos directly to those zones.'],
            ['Diagnose & plan', 'Make the diagnosis and build the treatment plan.'],
            ['Procedure or Rx', 'Procedure room: log start/end, materials. Or send the topical Rx via WhatsApp.'],
            ['Follow-up photos', 'Each follow-up auto-aligns photos to the same body-map zone. No more "wait, what angle was this?"'],
            ['Compare & decide', 'Side-by-side wipe between any two visits. Adjust plan, repeat.'],
        ],
        'pricingHead' => 'A real derma clinic, $34 a month.',
        'pricingBlurb' => 'Most dermatologists run the skin imaging module plus the essentials.',
        'pricingLabel' => 'Solo dermatologist',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Skin imaging module', '$11/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
            ['Diet plans', '$3/mo (add-on)'],
        ],
        'pricingTotal' => 34,
        'testimonialsHead' => 'What dermatologists say.',
        'testimonials' => [
            ['Dr. Sofia Marín', 'Madrid, Spain', 'The before/after compare convinced me to stay. The pricing convinced my accountant. We pay €34/month for what we use.'],
            ['Dr. Hannah Lin', 'Sydney, Australia', 'The lesion measurement tool is genuinely better than what we used at the hospital. Patients trust the numbers.'],
            ['Dr. Olu Adebayo', 'Lagos, Nigeria', 'My patients see the progress and stay the full course. Retention jumped from 60% to 88% in six months.'],
        ],
        'migrationBlurb' => 'Skin photos live everywhere — phones, drives, EMRs. We pull them all into the body-map, sorted by date and region.',
        'migrateFrom' => ['NextGen', 'ModMed', 'Mirror Medical', 'Canfield', 'Phone camera roll', 'Google Photos', 'Practo', 'Cliniko', 'Excel / CSV'],
        'ctaTitle' => 'Run a derma clinic that shows the change.',
        'ctaSub' => 'Start free. Turn on skin imaging when your first patient walks in.',
    ],

    'peds' => [
        'slug' => 'pediatricians',
        'label' => 'Pediatricians',
        'icon' => '👶',
        'heroV2' => [
            'badge' => 'Smart Software for Pediatric Clinics',
            'title' => 'Pediatric Clinic Management Software |',
            'titleAccent' => 'Complete Child & Clinic Management Solution',
            'tagline' => 'Simplify Your Pediatric Practice with',
            'body' => [
                'Manage growth charts, vaccination schedules, weight-based dosing, appointments and billing from one secure platform built for pediatric clinics.',
                'eClinicPro helps you care for every child from 0 to 18 with less admin — and tools tailored to how pediatricians actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional Pediatric Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your Pediatric Clinic?',
            'sub' => 'Children\'s care needs precise growth, vaccine and dosing tracking that paper records simply can\'t keep up with.',
            'challenges' => [
                ['Hand-plotted Growth Charts', 'Manual percentile plotting is slow and error-prone.'],
                ['Missed Vaccinations', 'Without reminders, vaccine doses are delayed or missed.'],
                ['Dosing Errors', 'Weight-based dosing done by hand risks mistakes.'],
                ['Lost Milestone Records', 'Developmental milestone checks are hard to track on paper.'],
                ['Worried, Under-informed Parents', 'Parents leave without a clear summary of the visit.'],
                ['Allergy Oversights', 'Feeding and drug allergies get missed across visits.'],
            ],
            'solutions' => [
                ['records', 'WHO Growth Charts', 'Auto-plot weight, height and head circumference.'],
                ['appointments', 'Vaccine Scheduler', 'Country-specific schedules with parent reminders.'],
                ['billing', 'Billing Automation', 'Generate invoices and track payments easily.'],
                ['inventory', 'Weight-based Dosing', 'Doses calculate from the latest weight, safely.'],
                ['reports', 'Reports & Analytics', 'Track vaccine rates, growth and revenue clearly.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Child Health',
            'ctaTitleEnd' => ', Not Paperwork.',
            'ctaSub' => 'EClinicPro automates your pediatric clinic so you spend more time with children and parents.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern Pediatric Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'Pediatric Software',
            'sub' => 'Everything you need to run a pediatric clinic efficiently and focus on what matters most – your young patients.',
            'cards' => [
                ['icon' => 'patient', 'title' => 'Child & Patient Management', 'items' => ['Complete digital child records', 'WHO growth charts (weight, height, HC)', 'Developmental milestone tracking', 'Allergy & feeding flags', 'Secure cloud storage'], 'mock' => 'patient'],
                ['icon' => 'calendar', 'title' => 'Appointment & Vaccine Management', 'items' => ['Online and offline booking', 'Country-specific vaccine scheduler', 'Parent reminders 30 days before doses', 'Automated SMS / WhatsApp reminders', 'Daily schedule overview'], 'mock' => 'calendar'],
                ['icon' => 'rx', 'title' => 'Prescription & Dosing', 'items' => ['Weight-based automatic dosing', 'Pediatric range warnings', 'Save frequently used medicines', 'Print and share prescriptions easily'], 'mock' => 'rx'],
                ['icon' => 'billing', 'title' => 'Billing and Invoice Management', 'items' => ['Professional invoices', 'Track payments (paid & due)', 'Vaccination package billing', 'Download and email invoices'], 'mock' => 'billing'],
                ['icon' => 'medicine', 'title' => 'Growth & Milestone Tools', 'items' => ['Percentile curve plotting', 'Age-appropriate milestone prompts', 'Vaccine stock tracking', 'Expiry & batch tracking'], 'mock' => 'medicine'],
                ['icon' => 'reports', 'title' => 'Reports and Analytics', 'items' => ['Daily patient reports', 'Vaccine on-time rate reports', 'Revenue and billing reports', 'Growth tracking statistics', 'Export reports for analysis'], 'mock' => 'reports'],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => ['Manage multiple pediatric branches', 'Separate doctor & schedule per branch', 'Role-based access for staff', 'Cloud-based access from anywhere'],
                'branches' => [['Head Clinic', 'Ahmedabad', true], ['Branch Clinic', 'Surat', false], ['Branch Clinic', 'Rajkot', false]],
                'users' => [['Dr. Amara Okonkwo', 'Admin', 'admin'], ['Dr. Neha Kulkarni', 'Pediatrician', 'doctor'], ['Anita Shah', 'Nurse', 'nurse'], ['Rohan Verma', 'Receptionist', 'reception']],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Tracking. Better Care. Better Practice.',
            'title' => 'Benefits of Using Pediatric Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps pediatricians:',
            'items' => [
                ['time', 'Save Administrative Time', 'Auto-plot growth and dosing to focus on children.'],
                ['paperwork', 'Reduce Paperwork', 'Go digital with charts, vaccines and milestones.'],
                ['experience', 'Improve Parent Experience', 'Clear summaries and reminders reassure parents.'],
                ['efficiency', 'Increase Clinic Efficiency', 'Streamline well-visits from weigh-in to summary.'],
                ['secure', 'Manage Records Securely', 'Store each child\'s data safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Track vaccine rates and growth with real data.'],
                ['followup', 'Improve Follow-up Management', 'Never miss a vaccine dose or well-visit.'],
                ['growth', 'Grow Your Practice Effectively', 'Engaged parents and reminders bring families back.'],
            ],
            'ctaTitle' => 'Smart Child Care. Better Parent Experience. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers pediatricians to run efficient clinics and care for every child.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your Pediatric Clinic',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your pediatric clinic operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Hand-plotted Charts', 'Manual percentile plotting is slow and inaccurate.'],
                ['appointments', 'Missed Vaccines', 'No reminders means delayed or missed doses.'],
                ['rx', 'Dosing Errors', 'Weight-based dosing by hand risks mistakes.'],
                ['billing', 'Billing Mistakes', 'Manual vaccine package billing causes errors.'],
                ['medicine', 'Vaccine Stock Issues', 'No batch or expiry tracking for vaccines.'],
                ['reports', 'No Proper Reports', 'Vaccine and growth reports are slow and inaccurate.'],
                ['clinic', 'Hard to Manage Branches', 'Coordinating multiple clinics manually is difficult.'],
            ],
            'compareRows' => [
                ['records', 'Growth Records'],
                ['appointments', 'Vaccine Scheduling'],
                ['rx', 'Weight-based Dosing'],
                ['billing', 'Billing & Invoices'],
                ['medicine', 'Milestone Tracking'],
                ['reports', 'Vaccine Reports'],
                ['clinic', 'Multi-Clinic Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient pediatric management.',
            'digitalItems' => [
                'WHO growth charts plotted automatically.',
                'Vaccine scheduler with parent reminders.',
                'Weight-based dosing with range warnings.',
                'Vaccination package billing and payment tracking.',
                'Developmental milestone prompts by age.',
                'Allergy and feeding flags across every visit.',
                'Instant vaccine, growth and revenue reports.',
                'Seamless multi-clinic and user management.',
            ],
            'ctaTitle' => 'Save Time. Improve Vaccine Rates. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart pediatric management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro Pediatric Clinic Management Software.',
            'items' => [
                ['software', 'What is Pediatric Clinic Management Software?', 'It is a digital solution that helps pediatricians manage growth charts, vaccinations, weight-based dosing, appointments, billing and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for small pediatric clinics?', 'Yes. EClinicPro works for solo pediatricians as well as large multi-branch children\'s clinics.'],
                ['history', 'Can I plot growth and track milestones digitally?', 'Yes. EClinicPro auto-plots WHO percentile charts and prompts age-appropriate developmental milestone checks.'],
                ['billing', 'Does EClinicPro support vaccination billing?', 'Yes. The software provides billing, vaccine package invoices, payment tracking and financial reporting.'],
                ['cloud', 'Is EClinicPro cloud-based?', 'Yes. You can access each child\'s records securely from anywhere, anytime.'],
            ],
        ],
        'headline' => ['Watch them grow, on ', 'real percentile', ' curves.'],
        'heroBlurb' => 'WHO growth charts, vaccination scheduler, weight-based dosing, parent-facing summaries — designed around how kids actually grow.',
        'heroProof' => ['540 peds clinics', '22 countries', 'From $19/mo'],
        'stats' => [['+38%', 'Vaccine on-time rate'], ['0', 'Dosing errors logged'], ['12 mo', 'Growth tracking'], ['4.9', 'Avg parent rating']],
        'featsHead' => ['Pediatric care, tooled properly.', 'For every child, from 0 to 18.'],
        'feats' => [
            ['🌱', 'WHO growth charts', 'Weight, height, head circumference, BMI — every visit plotted on WHO percentile bands.'],
            ['📅', 'Vaccine scheduler', "Country-specific schedules. Reminders go to the parent's WhatsApp 30 days before each dose."],
            ['℞', 'Weight-based dosing', "Enter the child's weight; doses calculate themselves. Pediatric range warnings catch outliers."],
            ['💬', 'Parent-facing summaries', 'After each visit, parents get a clean summary in plain language with next steps.'],
            ['📋', 'Developmental milestones', 'Auto-prompted milestone checks at 2/4/6/9/12/18/24-month visits. Track delays cleanly.'],
            ['🛡️', 'Allergy & feeding flags', 'Penicillin, peanut, lactose, gluten — flagged across every Rx and procedure.'],
        ],
        'workflowHead' => 'Every well-visit, the same five-step rhythm.',
        'workflow' => [
            ['Weigh & measure', 'Nurse enters weight, height, head circumference on tablet. Auto-plotted on percentile curve.'],
            ['Milestone check', 'System prompts the right age-appropriate milestones. You tap "met" or add notes.'],
            ['Vaccine review', "Schedule shows what's due today, what's coming up next month, what got missed."],
            ['Rx with auto-dose', 'Type the drug name; dose, frequency, and duration calculate from the latest weight.'],
            ['Parent summary', 'WhatsApp summary goes out: "You saw Dr. Okonkwo today. Sneha is at the 62nd percentile…"'],
        ],
        'pricingHead' => 'A real peds clinic, $25 a month.',
        'pricingBlurb' => 'Most pediatricians run the growth-chart module plus the basics.',
        'pricingLabel' => 'Solo pediatrician',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Growth charts module', '$5/mo'],
            ['Digital prescriptions', '$6/mo'],
            ['QR patient card', '$4/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices (lite)', '$5/mo'],
        ],
        'pricingTotal' => 25,
        'testimonialsHead' => 'What pediatricians say.',
        'testimonials' => [
            ['Dr. Amara Okonkwo', 'Lagos, Nigeria', 'Parents love the weight-based dosing and the WhatsApp summary. I love that I no longer fight a spreadsheet.'],
            ['Dr. Mei-Lin Chen', 'Taipei, Taiwan', 'The vaccine reminders single-handedly raised our on-time rate from 64% to 91%. My nurses sleep better.'],
            ['Dr. Andrés Vega', 'Bogotá, Colombia', "My patients' parents are now genuinely invested in their child's growth chart. They show me at every visit."],
        ],
        'migrationBlurb' => 'Pediatric records live in immunization registries, EMRs, and growth-tracking apps. We pull them all into one timeline.',
        'migrateFrom' => ['Practo', 'eClinicalWorks', 'OfficePractic', 'Pediatric Practice Manager', 'Govt. immunization registry', 'Excel / CSV', 'Paper card'],
        'ctaTitle' => 'Run a peds clinic that grows with every child.',
        'ctaSub' => 'Start free. Turn on growth charts at the first well-visit.',
    ],

    'physio' => [
        'slug' => 'physiotherapists',
        'label' => 'Physiotherapists',
        'icon' => '🤸',
        'heroV2' => [
            'badge' => 'Smart Software for Physiotherapy Clinics',
            'title' => 'Physiotherapy Clinic Management Software |',
            'titleAccent' => 'Complete Patient & Rehab Management Solution',
            'tagline' => 'Simplify Your Physiotherapy Practice with',
            'body' => [
                'Build exercise programs, track outcomes, manage appointments and billing from one secure platform built for physiotherapy clinics.',
                'eClinicPro helps you boost home-program adherence with less admin — and tools tailored to how physiotherapists actually work.',
            ],
        ],
        'whyChoose' => [
            'badge' => 'Challenges of Traditional Physiotherapy Management',
            'title' => 'Why Choose',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'for Your Physiotherapy Clinic?',
            'sub' => 'Rehab success depends on home adherence and outcome tracking — nearly impossible with paper programs and printouts.',
            'challenges' => [
                ['Low Home Adherence', 'Paper exercise sheets get lost and rarely followed.'],
                ['Unclear Exercises', 'Static drawings confuse patients on form and reps.'],
                ['No Outcome Tracking', 'ODI, NDI and other scales are hard to score manually.'],
                ['Missed Reassessments', 'Follow-up assessments slip without reminders.'],
                ['Billing Errors', 'Manual session and package billing causes mistakes.'],
                ['No Progress Visibility', 'Patients can\'t see improvement, so they drop off.'],
            ],
            'solutions' => [
                ['records', 'Exercise Video Library', '600+ HD videos patients follow at home.'],
                ['appointments', 'Smart Appointments', 'Schedule sessions and reassessments easily.'],
                ['billing', 'Billing Automation', 'Session and package billing with tracking.'],
                ['inventory', 'Adherence Tracking', 'See who did their exercises and auto-nudge.'],
                ['reports', 'Outcome Analytics', 'Auto-scored scales plotted over time.'],
            ],
            'ctaTitle' => 'Focus More on',
            'ctaHighlight' => 'Patient Recovery',
            'ctaTitleEnd' => ', Not Paperwork.',
            'ctaSub' => 'EClinicPro automates your physio clinic so you spend more time on hands-on care and recovery.',
        ],
        'keyFeatures' => [
            'badge' => 'All-in-One Solution for Modern Physiotherapy Clinics',
            'title' => 'Key Features of',
            'titleBrand' => 'EClinicPro',
            'titleSuffix' => 'Physiotherapy Software',
            'sub' => 'Everything you need to run a physiotherapy clinic efficiently and focus on what matters most – your patients\' recovery.',
            'cards' => [
                ['icon' => 'patient', 'title' => 'Patient & Assessment Management', 'items' => ['Complete digital patient records', 'Pain (VAS) & ROM logs per visit', 'Assessment & injury history', 'Outcome scale tracking (ODI, NDI)', 'Secure cloud storage'], 'mock' => 'patient'],
                ['icon' => 'calendar', 'title' => 'Appointment Management', 'items' => ['Online and offline booking', 'Session & slot scheduling', 'Reassessment reminders', 'Automated SMS / WhatsApp reminders', 'Daily schedule overview'], 'mock' => 'calendar'],
                ['icon' => 'rx', 'title' => 'Exercise Program Management', 'items' => ['600+ video exercise library', 'Weekly drag-and-drop program builder', 'Patient follow-along on WhatsApp', 'Sets, reps, hold and rest control'], 'mock' => 'rx'],
                ['icon' => 'billing', 'title' => 'Billing and Invoice Management', 'items' => ['Session & package billing', 'Track payments (paid & due)', 'Professional invoices', 'Download and email invoices'], 'mock' => 'billing'],
                ['icon' => 'medicine', 'title' => 'Outcome & Adherence Tools', 'items' => ['Auto-scored outcome scales', 'Adherence tracking & nudges', 'Pain & motion trend charts', 'Progress plotted over time'], 'mock' => 'medicine'],
                ['icon' => 'reports', 'title' => 'Reports and Analytics', 'items' => ['Daily patient reports', 'Adherence & outcome reports', 'Revenue and billing reports', 'Session statistics', 'Export reports for analysis'], 'mock' => 'reports'],
            ],
            'wideCard' => [
                'icon' => 'clinic',
                'title' => 'Multi-Clinic and Multi-User Support',
                'items' => ['Manage multiple physio branches', 'Separate therapist & schedule per branch', 'Role-based access for staff', 'Cloud-based access from anywhere'],
                'branches' => [['Head Clinic', 'Ahmedabad', true], ['Branch Clinic', 'Surat', false], ['Branch Clinic', 'Rajkot', false]],
                'users' => [['Dr. Maya Patel', 'Admin', 'admin'], ['Dr. Arjun Rao', 'Physiotherapist', 'doctor'], ['Anita Shah', 'Assistant', 'nurse'], ['Rohan Verma', 'Receptionist', 'reception']],
                'accessTitle' => 'Access your clinic data securely from anywhere, anytime.',
                'accessSub' => 'Secure. Reliable. Always Available.',
            ],
        ],
        'benefits' => [
            'badge' => 'Better Adherence. Better Care. Better Practice.',
            'title' => 'Benefits of Using Physiotherapy Clinic Management Software',
            'intro' => 'Using',
            'introBrand' => 'EClinicPro',
            'introSuffix' => 'helps physiotherapists:',
            'items' => [
                ['time', 'Save Administrative Time', 'Build and send programs in minutes, not on paper.'],
                ['paperwork', 'Reduce Paperwork', 'Go digital with programs, assessments and notes.'],
                ['experience', 'Improve Patient Experience', 'Follow-along videos make home programs easy.'],
                ['efficiency', 'Increase Clinic Efficiency', 'Streamline assessment, program and follow-up.'],
                ['secure', 'Manage Records Securely', 'Store assessments and outcomes safely in the cloud.'],
                ['reports', 'Generate Accurate Reports', 'Track adherence and outcomes with real data.'],
                ['followup', 'Improve Follow-up Management', 'Never miss a reassessment with smart reminders.'],
                ['growth', 'Grow Your Practice Effectively', 'Higher adherence and outcomes drive referrals.'],
            ],
            'ctaTitle' => 'Smart Rehab Management. Better Recovery. Stronger Practice Growth.',
            'ctaSub' => 'EClinicPro empowers physiotherapists to run efficient clinics and improve patient recovery.',
            'ctaTrust' => ['Secure', 'Reliable', 'Easy to Use'],
        ],
        'comparison' => [
            'badge' => 'Make the Smart Choice for Your Physio Clinic',
            'title' => 'Manual Management vs',
            'titleBrand' => 'EClinicPro',
            'sub' => 'See how EClinicPro transforms your physiotherapy clinic operations compared to traditional manual management.',
            'manualTitle' => 'Manual Management',
            'manualSub' => 'Time-consuming, error-prone and hard to manage.',
            'manualItems' => [
                ['records', 'Lost Exercise Sheets', 'Paper programs get lost and rarely followed.'],
                ['appointments', 'Missed Reassessments', 'No reminders means skipped follow-up reviews.'],
                ['rx', 'Confusing Exercises', 'Static drawings confuse patients on form.'],
                ['billing', 'Billing Mistakes', 'Manual session and package billing causes errors.'],
                ['medicine', 'No Outcome Tracking', 'Scoring scales by hand is slow and unreliable.'],
                ['reports', 'No Proper Reports', 'Adherence and outcome reports are inaccurate.'],
                ['clinic', 'Hard to Manage Branches', 'Coordinating therapists and branches is difficult.'],
            ],
            'compareRows' => [
                ['records', 'Assessment Records'],
                ['appointments', 'Session Scheduling'],
                ['rx', 'Exercise Programs'],
                ['billing', 'Session & Package Billing'],
                ['medicine', 'Outcome & Adherence'],
                ['reports', 'Progress Reports'],
                ['clinic', 'Multi-Clinic Support'],
            ],
            'digitalTitle' => 'EClinicPro',
            'digitalSub' => 'Smart, automated and efficient physiotherapy management.',
            'digitalItems' => [
                'Video programs patients follow at home.',
                'Drag-and-drop weekly program builder.',
                'WhatsApp follow-along with adherence tracking.',
                'Session and package billing with tracking.',
                'Auto-scored outcome scales plotted over time.',
                'Pain and ROM trends alongside outcomes.',
                'Instant adherence, outcome and revenue reports.',
                'Seamless multi-clinic and user management.',
            ],
            'ctaTitle' => 'Save Time. Boost Adherence. Grow Your Practice.',
            'ctaSub' => 'Switch to EClinicPro and experience the power of smart physiotherapy management.',
        ],
        'faq' => [
            'badge' => 'Get Clear Answers. Make Confident Decisions.',
            'title' => 'Frequently Asked',
            'titleAccent' => 'Questions',
            'sub' => 'Everything you need to know about EClinicPro Physiotherapy Clinic Management Software.',
            'items' => [
                ['software', 'What is Physiotherapy Clinic Management Software?', 'It is a digital solution that helps physiotherapists manage exercise programs, assessments, outcomes, appointments, billing and reports efficiently.'],
                ['clinic', 'Is EClinicPro suitable for solo physios?', 'Yes. EClinicPro works for solo physiotherapists as well as large multi-branch rehab and sports physio clinics.'],
                ['history', 'Can I build and send exercise programs digitally?', 'Yes. EClinicPro includes a 600+ video library and a weekly program builder that patients follow along on WhatsApp.'],
                ['billing', 'Does EClinicPro support session and package billing?', 'Yes. The software provides session and package billing with payment tracking and financial reporting.'],
                ['cloud', 'Is EClinicPro cloud-based?', 'Yes. You can access your assessments, programs and outcomes securely from anywhere, anytime.'],
            ],
        ],
        'headline' => ['Programs your patients ', 'actually', ' follow.'],
        'heroBlurb' => 'Build exercise programs from a 600-video library and send them to your patient as a follow-along plan on WhatsApp. Track adherence and outcomes.',
        'heroProof' => ['490 physio clinics', '19 countries', 'From $17/mo'],
        'stats' => [['600+', 'Exercise videos'], ['+62%', 'Home-program adherence'], ['8', 'Outcome scales'], ['4.8', 'Avg physio rating']],
        'featsHead' => ['Tools for clinic-and-home physiotherapy.', 'Built for adherence, not paperwork.'],
        'feats' => [
            ['🎥', 'Exercise video library', '600+ HD videos, multiple angles, voice-over in 8 languages. Filter by region, condition, equipment.'],
            ['📅', 'Weekly program builder', 'Drag exercises into a 7-day grid. Sets, reps, hold time, rest — set once, sent everywhere.'],
            ['💬', 'Patient follow-along', "Patient sees the day's program on WhatsApp with a tap-to-play video. Check off as they go."],
            ['📊', 'Outcome scales', 'ODI, NDI, DASH, Roland-Morris, SF-36 — auto-scored, plotted over time.'],
            ['📈', 'Adherence tracking', "See who did Monday's exercises and who didn't. Auto-nudge skipped sessions."],
            ['📋', 'Pain & motion logs', 'VAS pain score and ROM measurements per visit, plotted alongside outcome scales.'],
        ],
        'workflowHead' => 'From first assessment to discharge.',
        'workflow' => [
            ['Assess & score', 'Run a baseline ODI/NDI. Record VAS, ROM. Photo or video your manual assessment.'],
            ['Build the program', 'Drag exercises from the library into a weekly grid. Set reps, hold, intensity.'],
            ['Send to patient', 'WhatsApp link. Patient opens it on the bus home — videos play, exercises check off.'],
            ['Track adherence', 'Daily and weekly view: who did what, who skipped, who reported pain.'],
            ['Reassess at week 4', 'Rerun the scales. Outcome plot side-by-side with adherence. Adjust the program.'],
        ],
        'pricingHead' => 'A real physio practice, $22 a month.',
        'pricingBlurb' => 'Solo physios run on Starter plus the exercise program module.',
        'pricingLabel' => 'Solo physiotherapist',
        'pricingItems' => [
            ['Starter plan', 'Free'],
            ['Exercise plans module', '$8/mo'],
            ['Vitals & charts', '$5/mo'],
            ['Billing & invoices', '$9/mo'],
        ],
        'pricingTotal' => 22,
        'testimonialsHead' => 'What physios say.',
        'testimonials' => [
            ['Dr. Maya Patel', 'Bristol, UK', "My patients actually do their home programs now. Adherence went from 30% to 78% in three months. That's the whole job."],
            ['Dr. Tomás Silva', 'São Paulo, Brazil', 'The Portuguese voice-over in the videos changed everything. My patients trust the program because they can hear instructions in their language.'],
            ['Dr. Hyun-woo Park', 'Seoul, South Korea', 'I run a sports physio clinic. The outcome scales plus video feedback let me discharge confidently.'],
        ],
        'migrationBlurb' => 'Physio records are messy — assessment PDFs, video files, paper programs. We import everything and re-link it by patient.',
        'migrateFrom' => ['Cliniko', 'PracticeHub', 'Jane App', 'Physitrack', 'TheraNest', 'Google Drive videos', 'Excel / CSV', 'Paper programs'],
        'ctaTitle' => 'Run a physio practice your patients stick with.',
        'ctaSub' => 'Start free. Turn on exercise plans when you write your first program.',
    ],
];
