-- =====================================================================
-- /store taxonomy seed — GENERATED by build_store_category_seed.py.
-- Do not hand-edit: change the script rules and re-run.
-- Run AFTER Batch 3a (store_categories, store_nav_items, store_nav_item_targets,
-- store_concerns, store_concern_categories).
-- Re-runnable: upserts on slugs. NOTE re-running resets compliance fields and the
-- menu/goal mappings to these values (overwrites edits made in admin).
-- =====================================================================
SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- Departments (parent_id = 0). Compliance is set per SUBCATEGORY below.
-- ---------------------------------------------------------------------
INSERT INTO `store_categories`
    (`parent_id`, `slug`, `name`, `compliance_note`, `sort_order`)
VALUES
    (0, 'mother-baby', 'Mother & Baby', 'Top-level department recommended | Age suitability + food/device compliance', 1),
    (0, 'womens-health', 'Women''s Health & Wellness', 'Life-stage filters recommended', 2),
    (0, 'mens-health', 'Men''s Health & Wellness', 'Avoid unsupported therapeutic/hormonal claims', 3),
    (0, 'senior-wellness', 'Senior / 50+ Wellness', 'Strong diagnostics cross-sell', 4),
    (0, 'nutrition-supplements', 'Nutrition & Nutraceuticals', 'Verify FSSAI category/licence/claims', 5),
    (0, 'gut-digestive-health', 'Gut & Digestive Health', 'Dedicated Shop by Need category', 6),
    (0, 'sleep-stress', 'Sleep & Stress Management', 'Separate ingestible/non-ingestible', 7),
    (0, 'mental-wellness', 'Mental Wellness & Mindfulness', 'Consumer wellness; no treatment claims', 8),
    (0, 'fitness-sports-nutrition', 'Fitness & Sports Nutrition', 'Extra supplement/claims screening', 9),
    (0, 'home-health-monitoring', 'Home Health Monitoring', 'Medical-device compliance', 10),
    (0, 'first-aid-home-care', 'First Aid & Home Care', 'Screen drug-containing products', 11),
    (0, 'oral-dental-care', 'Oral / Dental Wellness', 'Separate device/cosmetic/drug items', 12),
    (0, 'eye-care', 'Eye Care', 'Medicated eye products need review', 13),
    (0, 'hair-scalp', 'Hair & Scalp Wellness', 'Avoid unsupported treatment claims', 14),
    (0, 'skin-personal-care', 'Skin & Personal Care', 'Cosmetic compliance/claims', 15),
    (0, 'personal-hygiene', 'Personal Hygiene', 'Repeat-purchase category', 16),
    (0, 'joint-bone-mobility', 'Joint, Bone & Mobility', 'Separate supplements/devices', 17),
    (0, 'home-wellness', 'Home Wellness', 'Non-ingestible wellness', 18),
    (0, 'ayurveda-herbal', 'Ayurveda / Herbal Wellness', 'Verify FSSAI/AYUSH applicability', 19),
    (0, 'healthy-food', 'Healthy Food & Functional Foods', 'Verify FSSAI labels/claims', 20),
    (0, 'condition-support', 'Condition-Support Wellness', 'Support positioning; no diagnose/treat/cure claims', 21)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `compliance_note` = VALUES(`compliance_note`),
    `sort_order` = VALUES(`sort_order`);

-- Mother & Baby (30 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'mother-baby');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'baby-skincare', 'Baby skincare', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 1),
    (@d, 'baby-body-wash', 'Baby body wash', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 2),
    (@d, 'baby-shampoo', 'Baby shampoo', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 3),
    (@d, 'baby-lotion', 'Baby lotion', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 4),
    (@d, 'baby-cream', 'Baby cream', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 5),
    (@d, 'baby-massage-oils', 'Baby massage oils', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 6),
    (@d, 'baby-powder', 'Baby powder', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 7),
    (@d, 'baby-wipes', 'Baby wipes', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 8),
    (@d, 'baby-diaper-rash-creams', 'Baby diaper rash creams', 'baby', 'cosmetic', NULL, 'review', 'Some creams are medicated (drug)', 0, 9),
    (@d, 'baby-laundry-products', 'Baby laundry products', 'baby', 'general', NULL, 'open', NULL, 0, 10),
    (@d, 'baby-oral-care', 'Baby oral care', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 11),
    (@d, 'baby-feeding-accessories', 'Baby feeding accessories', 'baby', 'general', NULL, 'open', NULL, 0, 12),
    (@d, 'baby-bottles', 'Baby bottles', 'baby', 'general', NULL, 'review', 'IMS Act covers feeding bottles: no promotion/discount (VERIFY)', 1, 13),
    (@d, 'bottle-cleaning-products', 'Bottle cleaning products', 'baby', 'general', NULL, 'open', NULL, 0, 14),
    (@d, 'breast-pumps', 'Breast pumps', 'pregnancy', 'medical_device', 'medical_device_registration', 'open', NULL, 0, 15),
    (@d, 'breastfeeding-and-nursing-accessories', 'Breastfeeding & nursing accessories', 'pregnancy', 'general', NULL, 'open', NULL, 0, 16),
    (@d, 'baby-thermometers', 'Baby thermometers', 'baby', 'medical_device', 'medical_device_registration', 'open', NULL, 0, 17),
    (@d, 'baby-nasal-aspirators', 'Baby nasal aspirators', 'baby', 'medical_device', 'medical_device_registration', 'open', NULL, 0, 18),
    (@d, 'baby-humidifiers', 'Baby humidifiers', 'baby', 'general', NULL, 'open', NULL, 0, 19),
    (@d, 'baby-safe-hygiene-products', 'Baby-safe hygiene products', 'baby', 'general', NULL, 'open', NULL, 0, 20),
    (@d, 'baby-nutrition-products', 'Baby nutrition products', 'baby', 'food_fssai', 'fssai_license', 'review', 'IMS Act: no promotion/discount of infant foods (VERIFY)', 1, 21),
    (@d, 'infant-toddler-food-products', 'Infant/toddler food products', 'baby', 'food_fssai', 'fssai_license', 'review', 'IMS Act: no promotion/discount of infant foods (VERIFY)', 1, 22),
    (@d, 'teething-products-and-accessories', 'Teething products & accessories', 'baby', 'general', NULL, 'open', NULL, 0, 23),
    (@d, 'baby-sun-protection', 'Baby sun protection', 'baby', 'cosmetic', NULL, 'open', NULL, 0, 24),
    (@d, 'pregnancy-wellness', 'Pregnancy wellness', 'pregnancy', 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 25),
    (@d, 'prenatal-nutrition', 'Prenatal nutrition', 'pregnancy', 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 26),
    (@d, 'postpartum-care', 'Postpartum care', 'pregnancy', 'general', NULL, 'open', NULL, 0, 27),
    (@d, 'lactation-support-products', 'Lactation-support products', 'pregnancy', 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 28),
    (@d, 'maternity-wear-and-support-belts', 'Maternity wear & support belts', 'pregnancy', 'general', NULL, 'open', NULL, 0, 29),
    (@d, 'pregnancy-pillows', 'Pregnancy pillows', 'pregnancy', 'general', NULL, 'open', NULL, 0, 30)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Women's Health & Wellness (18 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'womens-health');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'womens-multivitamins', 'Women''s multivitamins', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'iron-and-folate', 'Iron & folate', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'calcium-plus-vitamin-d', 'Calcium + Vitamin D', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'vitamin-b12', 'Vitamin B12', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'womens-probiotics', 'Women''s probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'pcos-wellness-products', 'PCOS wellness products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Condition claim risk', 0, 6),
    (@d, 'menstrual-wellness', 'Menstrual wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'period-pain-heating-products', 'Period pain/heating products', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'period-underwear', 'Period underwear', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'menstrual-cups', 'Menstrual cups', NULL, 'general', NULL, 'open', NULL, 0, 10),
    (@d, 'sanitary-products', 'Sanitary products', NULL, 'general', NULL, 'open', NULL, 0, 11),
    (@d, 'intimate-hygiene', 'Intimate hygiene', NULL, 'cosmetic', NULL, 'open', NULL, 0, 12),
    (@d, 'vaginal-ph-intimate-care-products', 'Vaginal pH/intimate-care products', NULL, 'cosmetic', NULL, 'review', 'Intimate-care claims', 0, 13),
    (@d, 'womens-protein-nutrition', 'Women''s protein/nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 14),
    (@d, 'hair-skin-nail-nutrition', 'Hair/skin/nail nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 15),
    (@d, 'menopause-wellness', 'Menopause wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 16),
    (@d, 'bone-health-products', 'Bone-health products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 17),
    (@d, 'womens-sexual-wellness-products', 'Women''s sexual wellness products', NULL, 'general', NULL, 'review', 'Sensitive category; claims + product-type (device/drug) check; source says ''subject to compliance''', 0, 18)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Men's Health & Wellness (15 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'mens-health');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'mens-multivitamins', 'Men''s multivitamins', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'mens-daily-nutrition', 'Men''s daily nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'protein', 'Protein', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'mens-wellness-support-products', 'Men''s wellness support products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'mens-probiotics', 'Men''s probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'hair-loss-nutrition', 'Hair-loss nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Therapeutic-claim risk', 0, 6),
    (@d, 'mens-skincare', 'Men''s skincare', NULL, 'cosmetic', NULL, 'open', NULL, 0, 7),
    (@d, 'beard-grooming', 'Beard/grooming', NULL, 'cosmetic', NULL, 'open', NULL, 0, 8),
    (@d, 'mens-intimate-hygiene', 'Men''s intimate hygiene', NULL, 'cosmetic', NULL, 'open', NULL, 0, 9),
    (@d, 'mens-sexual-wellness', 'Men''s sexual wellness', NULL, 'general', NULL, 'review', 'Sensitive category; claims + product-type (device/drug) check', 0, 10),
    (@d, 'fertility-support-nutrition', 'Fertility-support nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Therapeutic-claim risk', 0, 11),
    (@d, 'prostate-health-wellness', 'Prostate-health wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Therapeutic-claim risk', 0, 12),
    (@d, 'energy-and-performance', 'Energy & performance', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Performance/hormonal claim risk', 0, 13),
    (@d, 'sports-nutrition', 'Sports nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 14),
    (@d, 'recovery-products', 'Recovery products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 15)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Senior / 50+ Wellness (20 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'senior-wellness');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'joint-health', 'Joint health', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'bone-health', 'Bone health', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'calcium-plus-d3', 'Calcium + D3', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'vitamin-b12', 'Vitamin B12', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'omega-3', 'Omega-3', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'heart-health-nutrition', 'Heart-health nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 6),
    (@d, 'eye-health-nutrition', 'Eye-health nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'memory-cognitive-wellness', 'Memory/cognitive wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Cognitive claim risk', 0, 8),
    (@d, 'protein-for-seniors', 'Protein for seniors', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 9),
    (@d, 'digestive-health', 'Digestive health', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 10),
    (@d, 'probiotics', 'Probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 11),
    (@d, 'immunity', 'Immunity', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 12),
    (@d, 'mobility-support-products', 'Mobility/support products', NULL, 'general', NULL, 'open', NULL, 0, 13),
    (@d, 'walking-support-accessories', 'Walking/support accessories', NULL, 'general', NULL, 'open', NULL, 0, 14),
    (@d, 'blood-pressure-monitors', 'Blood-pressure monitors', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 15),
    (@d, 'glucose-monitors', 'Glucose monitors', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 16),
    (@d, 'pulse-oximeters', 'Pulse oximeters', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 17),
    (@d, 'digital-thermometers', 'Digital thermometers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 18),
    (@d, 'pill-organizers', 'Pill organizers', NULL, 'general', NULL, 'open', NULL, 0, 19),
    (@d, 'adult-diapers-incontinence-products', 'Adult diapers/incontinence products', NULL, 'general', NULL, 'open', NULL, 0, 20)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Nutrition & Nutraceuticals (29 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'nutrition-supplements');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'multivitamins', 'Multivitamins', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'minerals', 'Minerals', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'vitamin-d', 'Vitamin D', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'vitamin-b12', 'Vitamin B12', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'vitamin-c', 'Vitamin C', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'calcium', 'Calcium', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 6),
    (@d, 'magnesium', 'Magnesium', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'zinc', 'Zinc', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 8),
    (@d, 'iron', 'Iron', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 9),
    (@d, 'omega-3', 'Omega-3', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 10),
    (@d, 'probiotics', 'Probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 11),
    (@d, 'prebiotics', 'Prebiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 12),
    (@d, 'fibre', 'Fibre', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 13),
    (@d, 'electrolytes', 'Electrolytes', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 14),
    (@d, 'protein', 'Protein', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 15),
    (@d, 'plant-protein', 'Plant protein', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 16),
    (@d, 'collagen', 'Collagen', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 17),
    (@d, 'biotin', 'Biotin', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 18),
    (@d, 'coq10', 'CoQ10', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 19),
    (@d, 'ashwagandha', 'Ashwagandha', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 20),
    (@d, 'turmeric-curcumin', 'Turmeric/curcumin', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 21),
    (@d, 'herbal-wellness', 'Herbal wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 22),
    (@d, 'superfoods', 'Superfoods', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 23),
    (@d, 'greens', 'Greens', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 24),
    (@d, 'functional-beverages', 'Functional beverages', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 25),
    (@d, 'health-drinks', 'Health drinks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 26),
    (@d, 'nutrition-powders', 'Nutrition powders', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 27),
    (@d, 'effervescent-tablets', 'Effervescent tablets', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 28),
    (@d, 'oral-strips', 'Oral strips', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Some oral strips are drugs', 0, 29)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Gut & Digestive Health (11 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'gut-digestive-health');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'probiotics', 'Probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'prebiotics', 'Prebiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'digestive-enzymes', 'Digestive enzymes', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'fibre', 'Fibre', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'psyllium', 'Psyllium', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'digestive-herbal-products', 'Digestive herbal products', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 6),
    (@d, 'gut-health-powders', 'Gut-health powders', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'fermented-foods', 'Fermented foods', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 8),
    (@d, 'low-sugar-digestive-products', 'Low-sugar digestive products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 9),
    (@d, 'bloating-support-products', 'Bloating-support products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Condition claim risk', 0, 10),
    (@d, 'constipation-support-wellness-products', 'Constipation-support wellness products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Condition claim risk', 0, 11)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Sleep & Stress Management (13 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'sleep-stress');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'sleep-support-wellness-products', 'Sleep-support wellness products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Melatonin is prescription-only in India; screen ingredients', 0, 1),
    (@d, 'magnesium-products', 'Magnesium products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'herbal-teas', 'Herbal teas', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'relaxation-products', 'Relaxation products', NULL, 'general', NULL, 'open', NULL, 0, 4),
    (@d, 'aromatherapy', 'Aromatherapy', NULL, 'general', NULL, 'open', NULL, 0, 5),
    (@d, 'essential-oils', 'Essential oils', NULL, 'cosmetic', NULL, 'open', NULL, 0, 6),
    (@d, 'sleep-masks', 'Sleep masks', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'eye-masks', 'Eye masks', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'weighted-blankets', 'Weighted blankets', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'neck-eye-relaxation-products', 'Neck/eye relaxation products', NULL, 'general', NULL, 'open', NULL, 0, 10),
    (@d, 'meditation-accessories', 'Meditation accessories', NULL, 'general', NULL, 'open', NULL, 0, 11),
    (@d, 'stress-management-products', 'Stress-management products', NULL, 'general', NULL, 'open', NULL, 0, 12),
    (@d, 'sleep-trackers', 'Sleep trackers', NULL, 'general', NULL, 'open', NULL, 0, 13)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Mental Wellness & Mindfulness (9 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'mental-wellness');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'meditation-products', 'Meditation products', NULL, 'general', NULL, 'open', NULL, 0, 1),
    (@d, 'journals', 'Journals', NULL, 'general', NULL, 'open', NULL, 0, 2),
    (@d, 'mindfulness-products', 'Mindfulness products', NULL, 'general', NULL, 'open', NULL, 0, 3),
    (@d, 'breathing-devices', 'Breathing devices', NULL, 'general', NULL, 'open', NULL, 0, 4),
    (@d, 'relaxation-products', 'Relaxation products', NULL, 'general', NULL, 'open', NULL, 0, 5),
    (@d, 'sleep-products', 'Sleep products', NULL, 'general', NULL, 'open', NULL, 0, 6),
    (@d, 'stress-management-products', 'Stress-management products', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'aromatherapy', 'Aromatherapy', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'yoga-meditation-accessories', 'Yoga/meditation accessories', NULL, 'general', NULL, 'open', NULL, 0, 9)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Fitness & Sports Nutrition (18 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'fitness-sports-nutrition');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'whey-protein', 'Whey protein', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'plant-protein', 'Plant protein', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'mass-gainers', 'Mass gainers', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'electrolytes', 'Electrolytes', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'pre-workout', 'Pre-workout', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Stimulant ingredients screening', 0, 5),
    (@d, 'post-workout', 'Post-workout', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 6),
    (@d, 'creatine', 'Creatine', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'amino-acids', 'Amino acids', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 8),
    (@d, 'energy-products', 'Energy products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Stimulant ingredients screening', 0, 9),
    (@d, 'recovery-products', 'Recovery products', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 10),
    (@d, 'protein-bars', 'Protein bars', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 11),
    (@d, 'healthy-snacks', 'Healthy snacks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 12),
    (@d, 'hydration-products', 'Hydration products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 13),
    (@d, 'shakers', 'Shakers', NULL, 'general', NULL, 'open', NULL, 0, 14),
    (@d, 'fitness-accessories', 'Fitness accessories', NULL, 'general', NULL, 'open', NULL, 0, 15),
    (@d, 'resistance-bands', 'Resistance bands', NULL, 'general', NULL, 'open', NULL, 0, 16),
    (@d, 'foam-rollers', 'Foam rollers', NULL, 'general', NULL, 'open', NULL, 0, 17),
    (@d, 'massage-recovery-products', 'Massage/recovery products', NULL, 'general', NULL, 'open', NULL, 0, 18)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Home Health Monitoring (14 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'home-health-monitoring');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'digital-bp-monitors', 'Digital BP monitors', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 1),
    (@d, 'glucometers', 'Glucometers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 2),
    (@d, 'glucose-test-strips', 'Glucose test strips', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 3),
    (@d, 'pulse-oximeters', 'Pulse oximeters', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 4),
    (@d, 'digital-thermometers', 'Digital thermometers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 5),
    (@d, 'weighing-scales', 'Weighing scales', NULL, 'general', NULL, 'open', NULL, 0, 6),
    (@d, 'body-composition-monitors', 'Body-composition monitors', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'ecg-devices', 'ECG devices', NULL, 'medical_device', 'medical_device_registration', 'review', 'Regulated diagnostic device', 0, 8),
    (@d, 'smart-health-monitors', 'Smart health monitors', NULL, 'medical_device', 'medical_device_registration', 'review', 'Regulated diagnostic device', 0, 9),
    (@d, 'nebulisers', 'Nebulisers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 10),
    (@d, 'steam-inhalers', 'Steam inhalers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 11),
    (@d, 'heating-pads', 'Heating pads', NULL, 'general', NULL, 'open', NULL, 0, 12),
    (@d, 'tens-devices', 'TENS devices', NULL, 'medical_device', 'medical_device_registration', 'review', 'Regulated therapy device', 0, 13),
    (@d, 'medical-alert-devices', 'Medical alert devices', NULL, 'general', NULL, 'open', NULL, 0, 14)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- First Aid & Home Care (13 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'first-aid-home-care');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'first-aid-kits', 'First-aid kits', NULL, 'medical_device', 'medical_device_registration', 'review', 'Kits may contain drugs', 0, 1),
    (@d, 'bandages', 'Bandages', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 2),
    (@d, 'gauze', 'Gauze', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 3),
    (@d, 'medical-tape', 'Medical tape', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 4),
    (@d, 'antiseptic-products', 'Antiseptic products', NULL, 'drug_restricted', 'drug_license', 'blocked', 'Drug licence required; no drugs at launch (D3)', 0, 5),
    (@d, 'wound-care-products', 'Wound-care products', NULL, 'medical_device', 'medical_device_registration', 'review', 'Some wound-care products are medicated', 0, 6),
    (@d, 'hot-cold-packs', 'Hot/cold packs', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'heating-pads', 'Heating pads', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'ice-packs', 'Ice packs', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'disposable-gloves', 'Disposable gloves', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 10),
    (@d, 'masks', 'Masks', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 11),
    (@d, 'sanitisation-products', 'Sanitisation products', NULL, 'drug_restricted', 'drug_license', 'blocked', 'Drug licence required; no drugs at launch (D3)', 0, 12),
    (@d, 'digital-thermometers', 'Digital thermometers', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 13)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Oral / Dental Wellness (13 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'oral-dental-care');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'toothbrushes', 'Toothbrushes', NULL, 'general', NULL, 'open', NULL, 0, 1),
    (@d, 'electric-toothbrushes', 'Electric toothbrushes', NULL, 'general', NULL, 'open', NULL, 0, 2),
    (@d, 'kids-toothbrushes', 'Kids'' toothbrushes', NULL, 'general', NULL, 'open', NULL, 0, 3),
    (@d, 'toothpaste', 'Toothpaste', NULL, 'cosmetic', NULL, 'open', NULL, 0, 4),
    (@d, 'sensitive-teeth-products', 'Sensitive-teeth products', NULL, 'cosmetic', NULL, 'review', 'Some are drugs', 0, 5),
    (@d, 'mouthwash', 'Mouthwash', NULL, 'cosmetic', NULL, 'open', NULL, 0, 6),
    (@d, 'floss', 'Floss', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'interdental-brushes', 'Interdental brushes', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'tongue-cleaners', 'Tongue cleaners', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'whitening-products', 'Whitening products', NULL, 'cosmetic', NULL, 'review', 'Cosmetic-claim check', 0, 10),
    (@d, 'oral-probiotics', 'Oral probiotics', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 11),
    (@d, 'denture-care-products', 'Denture-care products', NULL, 'cosmetic', NULL, 'open', NULL, 0, 12),
    (@d, 'water-flossers', 'Water flossers', NULL, 'general', NULL, 'open', NULL, 0, 13)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Eye Care (7 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'eye-care');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'eye-comfort-lubricating-products', 'Eye comfort/lubricating products', NULL, 'drug_restricted', 'drug_license', 'blocked', 'Drug licence required; no drugs at launch (D3); source says ''subject to regulation''', 0, 1),
    (@d, 'eye-masks', 'Eye masks', NULL, 'general', NULL, 'open', NULL, 0, 2),
    (@d, 'eye-comfort-products', 'Eye-comfort products', NULL, 'general', NULL, 'open', NULL, 0, 3),
    (@d, 'blue-light-glasses', 'Blue-light glasses', NULL, 'general', NULL, 'open', NULL, 0, 4),
    (@d, 'eye-health-nutrition', 'Eye-health nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'contact-lens-accessories', 'Contact-lens accessories', NULL, 'general', NULL, 'open', NULL, 0, 6),
    (@d, 'lens-cleaning-products', 'Lens cleaning products', NULL, 'medical_device', 'medical_device_registration', 'open', NULL, 0, 7)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Hair & Scalp Wellness (11 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'hair-scalp');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'hair-supplements', 'Hair supplements', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'biotin', 'Biotin', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'collagen', 'Collagen', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'hair-oils', 'Hair oils', NULL, 'cosmetic', NULL, 'open', NULL, 0, 4),
    (@d, 'scalp-products', 'Scalp products', NULL, 'cosmetic', NULL, 'open', NULL, 0, 5),
    (@d, 'anti-dandruff-products', 'Anti-dandruff products', NULL, 'cosmetic', NULL, 'review', 'Medicated shampoos (e.g. ketoconazole) are drugs', 0, 6),
    (@d, 'hair-masks', 'Hair masks', NULL, 'cosmetic', NULL, 'open', NULL, 0, 7),
    (@d, 'hair-serums', 'Hair serums', NULL, 'cosmetic', NULL, 'open', NULL, 0, 8),
    (@d, 'shampoos', 'Shampoos', NULL, 'cosmetic', NULL, 'open', NULL, 0, 9),
    (@d, 'conditioners', 'Conditioners', NULL, 'cosmetic', NULL, 'open', NULL, 0, 10),
    (@d, 'hair-growth-wellness-products', 'Hair-growth wellness products', NULL, 'cosmetic', NULL, 'review', 'May contain drugs (e.g. minoxidil); claim risk', 0, 11)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Skin & Personal Care (14 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'skin-personal-care');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'face-care', 'Face care', NULL, 'cosmetic', NULL, 'open', NULL, 0, 1),
    (@d, 'body-care', 'Body care', NULL, 'cosmetic', NULL, 'open', NULL, 0, 2),
    (@d, 'moisturisers', 'Moisturisers', NULL, 'cosmetic', NULL, 'open', NULL, 0, 3),
    (@d, 'sunscreens', 'Sunscreens', NULL, 'cosmetic', NULL, 'open', NULL, 0, 4),
    (@d, 'cleansers', 'Cleansers', NULL, 'cosmetic', NULL, 'open', NULL, 0, 5),
    (@d, 'serums', 'Serums', NULL, 'cosmetic', NULL, 'open', NULL, 0, 6),
    (@d, 'acne-care-cosmetics', 'Acne-care cosmetics', NULL, 'cosmetic', NULL, 'open', NULL, 0, 7),
    (@d, 'anti-ageing-cosmetics', 'Anti-ageing cosmetics', NULL, 'cosmetic', NULL, 'open', NULL, 0, 8),
    (@d, 'body-lotions', 'Body lotions', NULL, 'cosmetic', NULL, 'open', NULL, 0, 9),
    (@d, 'hand-care', 'Hand care', NULL, 'cosmetic', NULL, 'open', NULL, 0, 10),
    (@d, 'foot-care', 'Foot care', NULL, 'cosmetic', NULL, 'open', NULL, 0, 11),
    (@d, 'lip-care', 'Lip care', NULL, 'cosmetic', NULL, 'open', NULL, 0, 12),
    (@d, 'natural-organic-skincare', 'Natural/organic skincare', NULL, 'cosmetic', NULL, 'open', NULL, 0, 13),
    (@d, 'sensitive-skin-products', 'Sensitive-skin products', NULL, 'cosmetic', NULL, 'open', NULL, 0, 14)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Personal Hygiene (10 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'personal-hygiene');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'hand-wash', 'Hand wash', NULL, 'cosmetic', NULL, 'open', NULL, 0, 1),
    (@d, 'sanitiser', 'Sanitiser', NULL, 'drug_restricted', 'drug_license', 'blocked', 'Drug licence required; no drugs at launch (D3)', 0, 2),
    (@d, 'body-wash', 'Body wash', NULL, 'cosmetic', NULL, 'open', NULL, 0, 3),
    (@d, 'intimate-hygiene', 'Intimate hygiene', NULL, 'cosmetic', NULL, 'open', NULL, 0, 4),
    (@d, 'feminine-hygiene', 'Feminine hygiene', NULL, 'general', NULL, 'open', NULL, 0, 5),
    (@d, 'oral-hygiene', 'Oral hygiene', NULL, 'cosmetic', NULL, 'open', NULL, 0, 6),
    (@d, 'deodorants', 'Deodorants', NULL, 'cosmetic', NULL, 'open', NULL, 0, 7),
    (@d, 'foot-hygiene', 'Foot hygiene', NULL, 'cosmetic', NULL, 'open', NULL, 0, 8),
    (@d, 'travel-hygiene-kits', 'Travel hygiene kits', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'personal-care-kits', 'Personal-care kits', NULL, 'general', NULL, 'open', NULL, 0, 10)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Joint, Bone & Mobility (12 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'joint-bone-mobility');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'joint-support-nutrition', 'Joint-support nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'calcium', 'Calcium', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'vitamin-d', 'Vitamin D', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'collagen', 'Collagen', NULL, 'nutraceutical_fssai', 'fssai_license', 'open', NULL, 0, 4),
    (@d, 'knee-supports', 'Knee supports', NULL, 'general', NULL, 'open', NULL, 0, 5),
    (@d, 'wrist-supports', 'Wrist supports', NULL, 'general', NULL, 'open', NULL, 0, 6),
    (@d, 'back-supports', 'Back supports', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'ankle-supports', 'Ankle supports', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'elbow-supports', 'Elbow supports', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'compression-products', 'Compression products', NULL, 'general', NULL, 'open', NULL, 0, 10),
    (@d, 'hot-cold-therapy', 'Hot/cold therapy', NULL, 'general', NULL, 'open', NULL, 0, 11),
    (@d, 'massage-devices', 'Massage devices', NULL, 'general', NULL, 'open', NULL, 0, 12)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Home Wellness (10 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'home-wellness');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'air-purifiers', 'Air purifiers', NULL, 'general', NULL, 'open', NULL, 0, 1),
    (@d, 'humidifiers', 'Humidifiers', NULL, 'general', NULL, 'open', NULL, 0, 2),
    (@d, 'dehumidifiers', 'Dehumidifiers', NULL, 'general', NULL, 'open', NULL, 0, 3),
    (@d, 'aroma-diffusers', 'Aroma diffusers', NULL, 'general', NULL, 'open', NULL, 0, 4),
    (@d, 'essential-oils', 'Essential oils', NULL, 'cosmetic', NULL, 'open', NULL, 0, 5),
    (@d, 'sleep-products', 'Sleep products', NULL, 'general', NULL, 'open', NULL, 0, 6),
    (@d, 'massage-products', 'Massage products', NULL, 'general', NULL, 'open', NULL, 0, 7),
    (@d, 'heating-products', 'Heating products', NULL, 'general', NULL, 'open', NULL, 0, 8),
    (@d, 'wellness-lighting', 'Wellness lighting', NULL, 'general', NULL, 'open', NULL, 0, 9),
    (@d, 'ergonomic-products', 'Ergonomic products', NULL, 'general', NULL, 'open', NULL, 0, 10)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Ayurveda / Herbal Wellness (10 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'ayurveda-herbal');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'herbal-supplements', 'Herbal supplements', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 1),
    (@d, 'ayurvedic-nutrition', 'Ayurvedic nutrition', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 2),
    (@d, 'herbal-teas', 'Herbal teas', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'herbal-oils', 'Herbal oils', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 4),
    (@d, 'ayurvedic-skincare', 'Ayurvedic skincare', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 5),
    (@d, 'ayurvedic-haircare', 'Ayurvedic haircare', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 6),
    (@d, 'digestive-wellness', 'Digestive wellness', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 7),
    (@d, 'stress-sleep-wellness', 'Stress/sleep wellness', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 8),
    (@d, 'immunity-wellness', 'Immunity wellness', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 9),
    (@d, 'massage-oils', 'Massage oils', NULL, 'ayush', 'ayush_license', 'open', NULL, 0, 10)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Healthy Food & Functional Foods (15 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'healthy-food');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'protein-snacks', 'Protein snacks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 1),
    (@d, 'protein-bars', 'Protein bars', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 2),
    (@d, 'low-sugar-snacks', 'Low-sugar snacks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 3),
    (@d, 'diabetic-friendly-foods', 'Diabetic-friendly foods', NULL, 'food_fssai', 'fssai_license', 'review', 'Condition claim risk', 0, 4),
    (@d, 'keto-products', 'Keto products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 5),
    (@d, 'high-fibre-foods', 'High-fibre foods', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 6),
    (@d, 'millet-products', 'Millet products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 7),
    (@d, 'healthy-breakfast-products', 'Healthy breakfast products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 8),
    (@d, 'functional-beverages', 'Functional beverages', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 9),
    (@d, 'electrolyte-drinks', 'Electrolyte drinks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 10),
    (@d, 'herbal-drinks', 'Herbal drinks', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 11),
    (@d, 'sugar-free-products', 'Sugar-free products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 12),
    (@d, 'superfoods', 'Superfoods', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 13),
    (@d, 'nuts-seeds', 'Nuts/seeds', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 14),
    (@d, 'healthy-cooking-products', 'Healthy cooking products', NULL, 'food_fssai', 'fssai_license', 'open', NULL, 0, 15)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- Condition-Support Wellness (11 subcategories)
SET @d := (SELECT `id` FROM `store_categories` WHERE `parent_id` = 0 AND `slug` = 'condition-support');
INSERT INTO `store_categories` (`parent_id`, `slug`, `name`, `group_key`, `regulatory_class`, `required_vendor_doc`, `listing_mode`, `review_reason`, `no_promotion`, `sort_order`)
VALUES
    (@d, 'diabetes-friendly-nutrition', 'Diabetes-friendly nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 1),
    (@d, 'pcos-wellness', 'PCOS wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Condition claim risk', 0, 2),
    (@d, 'thyroid-wellness', 'Thyroid wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 3),
    (@d, 'heart-health-nutrition', 'Heart-health nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 4),
    (@d, 'cholesterol-support-nutrition', 'Cholesterol-support nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 5),
    (@d, 'weight-management-products', 'Weight-management products', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Therapeutic-claim risk', 0, 6),
    (@d, 'liver-wellness', 'Liver wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 7),
    (@d, 'kidney-friendly-nutrition', 'Kidney-friendly nutrition', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 8),
    (@d, 'joint-wellness', 'Joint wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 9),
    (@d, 'immunity', 'Immunity', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 10),
    (@d, 'digestive-wellness', 'Digestive wellness', NULL, 'nutraceutical_fssai', 'fssai_license', 'review', 'Support positioning only; no diagnose/treat/cure claims', 0, 11)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `group_key` = VALUES(`group_key`),
    `regulatory_class` = VALUES(`regulatory_class`), `required_vendor_doc` = VALUES(`required_vendor_doc`),
    `listing_mode` = VALUES(`listing_mode`), `review_reason` = VALUES(`review_reason`),
    `no_promotion` = VALUES(`no_promotion`), `sort_order` = VALUES(`sort_order`);

-- ---------------------------------------------------------------------
-- "Shop by need" menu + homepage tiles
-- ---------------------------------------------------------------------
INSERT INTO `store_nav_items` (`section`, `label`, `slug`, `url`, `homepage_tile_order`, `sort_order`)
VALUES
    ('need', 'Baby & Kids', 'baby-kids', NULL, 3, 1),
    ('need', 'Women''s Health', 'womens-health', NULL, 0, 2),
    ('need', 'Men''s Health', 'mens-health', NULL, 0, 3),
    ('need', '50+ & Senior Care', 'senior-care', NULL, 6, 4),
    ('need', 'Preventive Health', 'preventive-health', '/lab', 0, 5),
    ('need', 'Nutrition & Supplements', 'nutrition-supplements', NULL, 1, 6),
    ('need', 'Gut Health', 'gut-health', NULL, 0, 7),
    ('need', 'Sleep & Stress', 'sleep-stress', NULL, 0, 8),
    ('need', 'Fitness & Sports', 'fitness-sports', NULL, 0, 9),
    ('need', 'Home Health Devices', 'home-health-devices', NULL, 4, 10),
    ('need', 'First Aid & Home Care', 'first-aid-home-care', NULL, 0, 11),
    ('need', 'Oral Care', 'oral-care', NULL, 0, 12),
    ('need', 'Eye Care', 'eye-care', NULL, 0, 13),
    ('need', 'Hair & Skin', 'hair-skin', NULL, 2, 14),
    ('need', 'Personal Hygiene', 'personal-hygiene', NULL, 5, 15),
    ('need', 'Joint & Bone', 'joint-bone', NULL, 0, 16),
    ('need', 'Ayurveda & Herbal', 'ayurveda-herbal', NULL, 0, 17),
    ('need', 'Healthy Food & Beverages', 'healthy-food', NULL, 0, 18),
    ('need', 'Pregnancy & Mother Care', 'pregnancy-mother-care', NULL, 0, 19),
    ('need', 'Home Wellness', 'home-wellness', NULL, 0, 20)
ON DUPLICATE KEY UPDATE `label` = VALUES(`label`), `url` = VALUES(`url`),
    `homepage_tile_order` = VALUES(`homepage_tile_order`), `sort_order` = VALUES(`sort_order`);

-- Reset + rebuild the mappings for the seeded menu items.
DELETE t FROM `store_nav_item_targets` t
JOIN `store_nav_items` n ON n.id = t.nav_item_id
WHERE n.slug IN ('baby-kids', 'womens-health', 'mens-health', 'senior-care', 'preventive-health', 'nutrition-supplements', 'gut-health', 'sleep-stress', 'fitness-sports', 'home-health-devices', 'first-aid-home-care', 'oral-care', 'eye-care', 'hair-skin', 'personal-hygiene', 'joint-bone', 'ayurveda-herbal', 'healthy-food', 'pregnancy-mother-care', 'home-wellness');
-- Baby & Kids
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, c.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'baby-kids'
  AND (d.slug, c.slug) IN (
       ('mother-baby', 'baby-skincare'),
       ('mother-baby', 'baby-body-wash'),
       ('mother-baby', 'baby-shampoo'),
       ('mother-baby', 'baby-lotion'),
       ('mother-baby', 'baby-cream'),
       ('mother-baby', 'baby-massage-oils'),
       ('mother-baby', 'baby-powder'),
       ('mother-baby', 'baby-wipes'),
       ('mother-baby', 'baby-diaper-rash-creams'),
       ('mother-baby', 'baby-laundry-products'),
       ('mother-baby', 'baby-oral-care'),
       ('mother-baby', 'baby-feeding-accessories'),
       ('mother-baby', 'baby-bottles'),
       ('mother-baby', 'bottle-cleaning-products'),
       ('mother-baby', 'baby-thermometers'),
       ('mother-baby', 'baby-nasal-aspirators'),
       ('mother-baby', 'baby-humidifiers'),
       ('mother-baby', 'baby-safe-hygiene-products'),
       ('mother-baby', 'baby-nutrition-products'),
       ('mother-baby', 'infant-toddler-food-products'),
       ('mother-baby', 'teething-products-and-accessories'),
       ('mother-baby', 'baby-sun-protection'));
-- Women's Health
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'womens-health' AND d.slug IN ('womens-health');
-- Men's Health
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'mens-health' AND d.slug IN ('mens-health');
-- 50+ & Senior Care
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'senior-care' AND d.slug IN ('senior-wellness');
-- Nutrition & Supplements
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'nutrition-supplements' AND d.slug IN ('nutrition-supplements');
-- Gut Health
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'gut-health' AND d.slug IN ('gut-digestive-health');
-- Sleep & Stress
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'sleep-stress' AND d.slug IN ('sleep-stress', 'mental-wellness');
-- Fitness & Sports
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'fitness-sports' AND d.slug IN ('fitness-sports-nutrition');
-- Home Health Devices
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'home-health-devices' AND d.slug IN ('home-health-monitoring');
-- First Aid & Home Care
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'first-aid-home-care' AND d.slug IN ('first-aid-home-care');
-- Oral Care
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'oral-care' AND d.slug IN ('oral-dental-care');
-- Eye Care
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'eye-care' AND d.slug IN ('eye-care');
-- Hair & Skin
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'hair-skin' AND d.slug IN ('hair-scalp', 'skin-personal-care');
-- Personal Hygiene
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'personal-hygiene' AND d.slug IN ('personal-hygiene');
-- Joint & Bone
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'joint-bone' AND d.slug IN ('joint-bone-mobility');
-- Ayurveda & Herbal
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'ayurveda-herbal' AND d.slug IN ('ayurveda-herbal');
-- Healthy Food & Beverages
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'healthy-food' AND d.slug IN ('healthy-food');
-- Pregnancy & Mother Care
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, c.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'pregnancy-mother-care'
  AND (d.slug, c.slug) IN (
       ('mother-baby', 'breast-pumps'),
       ('mother-baby', 'breastfeeding-and-nursing-accessories'),
       ('mother-baby', 'pregnancy-wellness'),
       ('mother-baby', 'prenatal-nutrition'),
       ('mother-baby', 'postpartum-care'),
       ('mother-baby', 'lactation-support-products'),
       ('mother-baby', 'maternity-wear-and-support-belts'),
       ('mother-baby', 'pregnancy-pillows'));
-- Home Wellness
INSERT IGNORE INTO `store_nav_item_targets` (`nav_item_id`, `category_id`)
SELECT o.id, d.id FROM `store_nav_items` o
JOIN `store_categories` d ON d.parent_id = 0
WHERE o.slug = 'home-wellness' AND d.slug IN ('home-wellness');

-- ---------------------------------------------------------------------
-- "Shop by health goal"
-- ---------------------------------------------------------------------
INSERT INTO `store_concerns` (`slug`, `name`, `sort_order`)
VALUES
    ('immunity', 'Immunity', 1),
    ('energy', 'Energy', 2),
    ('sleep', 'Sleep', 3),
    ('gut-health', 'Gut Health', 4),
    ('weight-management', 'Weight Management', 5),
    ('womens-wellness', 'Women''s Wellness', 6),
    ('mens-wellness', 'Men''s Wellness', 7),
    ('kids-wellness', 'Kids'' Wellness', 8),
    ('hair-and-skin', 'Hair & Skin', 9),
    ('joint-and-bone', 'Joint & Bone', 10),
    ('heart-wellness', 'Heart Wellness', 11),
    ('diabetes-friendly', 'Diabetes-Friendly', 12),
    ('fitness-and-recovery', 'Fitness & Recovery', 13)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `sort_order` = VALUES(`sort_order`);

DELETE cc FROM `store_concern_categories` cc
JOIN `store_concerns` o ON o.id = cc.concern_id
WHERE o.slug IN ('immunity', 'energy', 'sleep', 'gut-health', 'weight-management', 'womens-wellness', 'mens-wellness', 'kids-wellness', 'hair-and-skin', 'joint-and-bone', 'heart-wellness', 'diabetes-friendly', 'fitness-and-recovery');
-- Immunity
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'immunity'
  AND (d.slug, c.slug) IN (
       ('senior-wellness', 'immunity'),
       ('nutrition-supplements', 'vitamin-c'),
       ('nutrition-supplements', 'zinc'),
       ('ayurveda-herbal', 'immunity-wellness'),
       ('condition-support', 'immunity'));
-- Energy
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'energy'
  AND (d.slug, c.slug) IN (
       ('womens-health', 'womens-multivitamins'),
       ('womens-health', 'vitamin-b12'),
       ('mens-health', 'mens-multivitamins'),
       ('mens-health', 'energy-and-performance'),
       ('senior-wellness', 'vitamin-b12'),
       ('nutrition-supplements', 'multivitamins'),
       ('nutrition-supplements', 'vitamin-b12'),
       ('nutrition-supplements', 'electrolytes'),
       ('fitness-sports-nutrition', 'electrolytes'),
       ('fitness-sports-nutrition', 'energy-products'),
       ('healthy-food', 'electrolyte-drinks'));
-- Sleep
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'sleep'
  AND (d.slug, c.slug) IN (
       ('nutrition-supplements', 'magnesium'),
       ('sleep-stress', 'sleep-support-wellness-products'),
       ('sleep-stress', 'magnesium-products'),
       ('sleep-stress', 'relaxation-products'),
       ('sleep-stress', 'sleep-masks'),
       ('sleep-stress', 'weighted-blankets'),
       ('sleep-stress', 'neck-eye-relaxation-products'),
       ('sleep-stress', 'sleep-trackers'),
       ('mental-wellness', 'relaxation-products'),
       ('mental-wellness', 'sleep-products'),
       ('home-wellness', 'sleep-products'),
       ('ayurveda-herbal', 'stress-sleep-wellness'));
-- Gut Health
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'gut-health'
  AND (d.slug, c.slug) IN (
       ('womens-health', 'womens-probiotics'),
       ('mens-health', 'mens-probiotics'),
       ('senior-wellness', 'digestive-health'),
       ('senior-wellness', 'probiotics'),
       ('nutrition-supplements', 'probiotics'),
       ('nutrition-supplements', 'prebiotics'),
       ('nutrition-supplements', 'fibre'),
       ('gut-digestive-health', 'probiotics'),
       ('gut-digestive-health', 'prebiotics'),
       ('gut-digestive-health', 'digestive-enzymes'),
       ('gut-digestive-health', 'fibre'),
       ('gut-digestive-health', 'psyllium'),
       ('gut-digestive-health', 'digestive-herbal-products'),
       ('gut-digestive-health', 'gut-health-powders'),
       ('gut-digestive-health', 'fermented-foods'),
       ('gut-digestive-health', 'low-sugar-digestive-products'),
       ('gut-digestive-health', 'bloating-support-products'),
       ('gut-digestive-health', 'constipation-support-wellness-products'),
       ('oral-dental-care', 'oral-probiotics'),
       ('ayurveda-herbal', 'digestive-wellness'),
       ('healthy-food', 'high-fibre-foods'),
       ('condition-support', 'digestive-wellness'));
-- Weight Management
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'weight-management'
  AND (d.slug, c.slug) IN (
       ('gut-digestive-health', 'low-sugar-digestive-products'),
       ('healthy-food', 'low-sugar-snacks'),
       ('healthy-food', 'keto-products'),
       ('healthy-food', 'high-fibre-foods'),
       ('healthy-food', 'sugar-free-products'),
       ('condition-support', 'weight-management-products'));
-- Women's Wellness
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'womens-wellness'
  AND (d.slug, c.slug) IN (
       ('womens-health', 'womens-multivitamins'),
       ('womens-health', 'iron-and-folate'),
       ('womens-health', 'calcium-plus-vitamin-d'),
       ('womens-health', 'vitamin-b12'),
       ('womens-health', 'womens-probiotics'),
       ('womens-health', 'pcos-wellness-products'),
       ('womens-health', 'menstrual-wellness'),
       ('womens-health', 'period-pain-heating-products'),
       ('womens-health', 'period-underwear'),
       ('womens-health', 'menstrual-cups'),
       ('womens-health', 'sanitary-products'),
       ('womens-health', 'intimate-hygiene'),
       ('womens-health', 'vaginal-ph-intimate-care-products'),
       ('womens-health', 'womens-protein-nutrition'),
       ('womens-health', 'hair-skin-nail-nutrition'),
       ('womens-health', 'menopause-wellness'),
       ('womens-health', 'bone-health-products'),
       ('womens-health', 'womens-sexual-wellness-products'));
-- Men's Wellness
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'mens-wellness'
  AND (d.slug, c.slug) IN (
       ('mens-health', 'mens-multivitamins'),
       ('mens-health', 'mens-daily-nutrition'),
       ('mens-health', 'protein'),
       ('mens-health', 'mens-wellness-support-products'),
       ('mens-health', 'mens-probiotics'),
       ('mens-health', 'hair-loss-nutrition'),
       ('mens-health', 'mens-skincare'),
       ('mens-health', 'beard-grooming'),
       ('mens-health', 'mens-intimate-hygiene'),
       ('mens-health', 'mens-sexual-wellness'),
       ('mens-health', 'fertility-support-nutrition'),
       ('mens-health', 'prostate-health-wellness'),
       ('mens-health', 'energy-and-performance'),
       ('mens-health', 'sports-nutrition'),
       ('mens-health', 'recovery-products'));
-- Kids' Wellness
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'kids-wellness'
  AND (d.slug, c.slug) IN (
       ('mother-baby', 'baby-skincare'),
       ('mother-baby', 'baby-body-wash'),
       ('mother-baby', 'baby-shampoo'),
       ('mother-baby', 'baby-lotion'),
       ('mother-baby', 'baby-cream'),
       ('mother-baby', 'baby-massage-oils'),
       ('mother-baby', 'baby-powder'),
       ('mother-baby', 'baby-wipes'),
       ('mother-baby', 'baby-diaper-rash-creams'),
       ('mother-baby', 'baby-laundry-products'),
       ('mother-baby', 'baby-oral-care'),
       ('mother-baby', 'baby-feeding-accessories'),
       ('mother-baby', 'baby-bottles'),
       ('mother-baby', 'bottle-cleaning-products'),
       ('mother-baby', 'baby-thermometers'),
       ('mother-baby', 'baby-nasal-aspirators'),
       ('mother-baby', 'baby-humidifiers'),
       ('mother-baby', 'baby-safe-hygiene-products'),
       ('mother-baby', 'baby-nutrition-products'),
       ('mother-baby', 'infant-toddler-food-products'),
       ('mother-baby', 'teething-products-and-accessories'),
       ('mother-baby', 'baby-sun-protection'));
-- Hair & Skin
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'hair-and-skin'
  AND (d.slug, c.slug) IN (
       ('hair-scalp', 'hair-supplements'),
       ('hair-scalp', 'biotin'),
       ('hair-scalp', 'collagen'),
       ('hair-scalp', 'hair-oils'),
       ('hair-scalp', 'scalp-products'),
       ('hair-scalp', 'anti-dandruff-products'),
       ('hair-scalp', 'hair-masks'),
       ('hair-scalp', 'hair-serums'),
       ('hair-scalp', 'shampoos'),
       ('hair-scalp', 'conditioners'),
       ('hair-scalp', 'hair-growth-wellness-products'),
       ('skin-personal-care', 'face-care'),
       ('skin-personal-care', 'body-care'),
       ('skin-personal-care', 'moisturisers'),
       ('skin-personal-care', 'sunscreens'),
       ('skin-personal-care', 'cleansers'),
       ('skin-personal-care', 'serums'),
       ('skin-personal-care', 'acne-care-cosmetics'),
       ('skin-personal-care', 'anti-ageing-cosmetics'),
       ('skin-personal-care', 'body-lotions'),
       ('skin-personal-care', 'hand-care'),
       ('skin-personal-care', 'foot-care'),
       ('skin-personal-care', 'lip-care'),
       ('skin-personal-care', 'natural-organic-skincare'),
       ('skin-personal-care', 'sensitive-skin-products'));
-- Joint & Bone
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'joint-and-bone'
  AND (d.slug, c.slug) IN (
       ('womens-health', 'calcium-plus-vitamin-d'),
       ('womens-health', 'bone-health-products'),
       ('senior-wellness', 'joint-health'),
       ('senior-wellness', 'bone-health'),
       ('senior-wellness', 'calcium-plus-d3'),
       ('nutrition-supplements', 'vitamin-d'),
       ('nutrition-supplements', 'calcium'),
       ('nutrition-supplements', 'collagen'),
       ('hair-scalp', 'collagen'),
       ('joint-bone-mobility', 'joint-support-nutrition'),
       ('joint-bone-mobility', 'calcium'),
       ('joint-bone-mobility', 'vitamin-d'),
       ('joint-bone-mobility', 'collagen'),
       ('joint-bone-mobility', 'knee-supports'),
       ('joint-bone-mobility', 'wrist-supports'),
       ('joint-bone-mobility', 'back-supports'),
       ('joint-bone-mobility', 'ankle-supports'),
       ('joint-bone-mobility', 'elbow-supports'),
       ('joint-bone-mobility', 'compression-products'),
       ('joint-bone-mobility', 'hot-cold-therapy'),
       ('joint-bone-mobility', 'massage-devices'),
       ('condition-support', 'joint-wellness'));
-- Heart Wellness
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'heart-wellness'
  AND (d.slug, c.slug) IN (
       ('senior-wellness', 'omega-3'),
       ('senior-wellness', 'heart-health-nutrition'),
       ('senior-wellness', 'blood-pressure-monitors'),
       ('nutrition-supplements', 'omega-3'),
       ('nutrition-supplements', 'coq10'),
       ('home-health-monitoring', 'digital-bp-monitors'),
       ('condition-support', 'heart-health-nutrition'),
       ('condition-support', 'cholesterol-support-nutrition'));
-- Diabetes-Friendly
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'diabetes-friendly'
  AND (d.slug, c.slug) IN (
       ('senior-wellness', 'glucose-monitors'),
       ('gut-digestive-health', 'low-sugar-digestive-products'),
       ('home-health-monitoring', 'glucometers'),
       ('home-health-monitoring', 'glucose-test-strips'),
       ('healthy-food', 'low-sugar-snacks'),
       ('healthy-food', 'diabetic-friendly-foods'),
       ('healthy-food', 'sugar-free-products'),
       ('condition-support', 'diabetes-friendly-nutrition'));
-- Fitness & Recovery
INSERT IGNORE INTO `store_concern_categories` (`concern_id`, `category_id`)
SELECT o.id, c.id FROM `store_concerns` o
JOIN `store_categories` d ON d.parent_id = 0
JOIN `store_categories` c ON c.parent_id = d.id
WHERE o.slug = 'fitness-and-recovery'
  AND (d.slug, c.slug) IN (
       ('mens-health', 'recovery-products'),
       ('fitness-sports-nutrition', 'whey-protein'),
       ('fitness-sports-nutrition', 'plant-protein'),
       ('fitness-sports-nutrition', 'mass-gainers'),
       ('fitness-sports-nutrition', 'electrolytes'),
       ('fitness-sports-nutrition', 'pre-workout'),
       ('fitness-sports-nutrition', 'post-workout'),
       ('fitness-sports-nutrition', 'creatine'),
       ('fitness-sports-nutrition', 'amino-acids'),
       ('fitness-sports-nutrition', 'energy-products'),
       ('fitness-sports-nutrition', 'recovery-products'),
       ('fitness-sports-nutrition', 'protein-bars'),
       ('fitness-sports-nutrition', 'healthy-snacks'),
       ('fitness-sports-nutrition', 'hydration-products'),
       ('fitness-sports-nutrition', 'shakers'),
       ('fitness-sports-nutrition', 'fitness-accessories'),
       ('fitness-sports-nutrition', 'resistance-bands'),
       ('fitness-sports-nutrition', 'foam-rollers'),
       ('fitness-sports-nutrition', 'massage-recovery-products'));
