// Data for all 6 specialty landing pages
window.SPECIALTY_CONFIGS = {
  dental: {
    id: 'dental', label: 'Dentists', mockKey: 'dental',
    href: 'for-dentists.html',
    headline: { before: 'A clinic OS that thinks in ', accent: 'teeth', after: ', not in spreadsheets.' },
    heroBlurb: 'Visual charting, treatment plans your patients understand, and recall that runs itself. Built with dentists in 14 countries.',
    heroProof: ['412 dental clinics', '14 countries', 'From $13/mo'],
    stats: [
      { v: '+71%', l: 'Recall rate vs paper' },
      { v: '+30%', l: 'Treatment-plan acceptance' },
      { v: '−42%', l: 'Time charting per patient' },
      { v: '4.9', l: 'Avg dentist rating' },
    ],
    featsHead: { h: 'Six things every dental clinic needs.', h2: "None of the stuff you don't." },
    feats: [
      { i: 'tooth', t: 'Visual dental chart', d: 'FDI, Palmer, or Universal numbering. Tap a tooth — see every note, image, and procedure since the first visit.' },
      { i: 'image', t: 'Per-tooth imaging', d: 'X-rays, intraoral photos, scans — attach to a tooth, a quadrant, or the whole arch. Drag, drop, done.' },
      { i: 'invoice', t: 'Treatment plans + quotes', d: 'Plan a course of work, send a quote your patient can accept on WhatsApp, track each visit against it.' },
      { i: 'cal', t: 'Recall by procedure', d: '6-month cleanings, 3-month perio, annual whitening — auto-scheduled reminders that book themselves.' },
      { i: 'rx', t: 'Dental-specific Rx', d: 'Antibiotics, analgesics, fluoride — pre-loaded with dose templates dental colleges actually use.' },
      { i: 'pill', t: 'Implant & material inventory', d: 'Track every implant by lot. Expiry alerts before the next big patient lands in your chair.' },
    ],
    workflowHead: 'From check-in to recall, in five steps.',
    workflow: [
      { t: 'Patient arrives', d: 'Receptionist scans the QR card. Chart loads with last visit, allergies, payment status.' },
      { t: 'You chart in the chair', d: 'Open the dental chart on iPad. Tap tooth 16, mark a caries class II, attach a photo — 20 seconds.' },
      { t: 'Build the plan', d: 'Drag procedures into a multi-visit treatment plan with materials and time blocks.' },
      { t: 'Quote sent on WhatsApp', d: 'Patient gets a clean PDF with line items, total, and an "Accept & book" link. No printer.' },
      { t: 'Recall, automated', d: 'Six months later, the system books them in for cleaning and sends the reminder.' },
    ],
    pricingHead: 'A real dental clinic, $33 a month.',
    pricingBlurb: 'Most single-chair dentists run on Starter plus a few targeted modules. Here\'s a real configuration.',
    pricingLabel: 'Single-chair dental clinic',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Dental charting module', '$9/mo'],
      ['Digital prescriptions', '$6/mo'],
      ['Billing & invoices', '$9/mo'],
      ['Analytics', '$9/mo'],
    ],
    pricingTotal: 33,
    testimonialsHead: 'What dentists say.',
    testimonials: [
      { n: 'Dr. James Whitfield', s: 'Toronto, Canada', q: 'I ran paper-and-Excel chairside for 14 years. We switched in a long weekend and our recall rate went from 38% to 71% in the first quarter.' },
      { n: 'Dr. Ananya Rao', s: 'Bangalore, India', q: 'The treatment plan PDF is so clean my patients actually read it. Case acceptance up 30%.' },
      { n: 'Dr. Yusuf El-Sayed', s: 'Dubai, UAE', q: 'Multilingual quotes in English and Arabic with the right insurance codes. Nothing else does this for under $100/month.' },
    ],
    migrationBlurb: 'If you have over 500 records, our team handles migration end-to-end. We import from any of the systems below — and most spreadsheets.',
    migrateFrom: ['Dentrix', 'Eaglesoft', 'Open Dental', 'Curve', 'Practo', 'Cliniko', 'Drchrono', 'SimplePractice', 'Excel / CSV', 'Paper register'],
    ctaTitle: 'Run a dental clinic that thinks in teeth.',
    ctaSub: "Start free. Add the dental module when you're ready.",
  },

  gp: {
    id: 'gp', label: 'GPs', mockKey: 'gp',
    href: 'for-gps.html',
    headline: { before: 'For the everyday doctor, ', accent: 'finally', after: ' given great tools.' },
    heroBlurb: 'OPD-ready out of the box. Triage, vitals, common Rx templates, and a fast walk-in flow — the GP basics, beautifully.',
    heroProof: ['1,420 GP clinics', '32 countries', 'From $15/mo'],
    stats: [
      { v: '8 min', l: 'Avg wait time saved' },
      { v: '−55%', l: 'Time at front desk' },
      { v: '+22%', l: 'Repeat visit rate' },
      { v: '4.8', l: 'Avg GP rating' },
    ],
    featsHead: { h: 'Built for the rhythm of a busy OPD.', h2: 'Triage, treat, recall.' },
    feats: [
      { i: 'bolt', t: 'Walk-in triage', d: 'Add a walk-in in 5 seconds with severity. The queue updates everyone in real time.' },
      { i: 'chart', t: 'Vitals on entry', d: 'Nurse captures vitals on a tablet. They\'re on your screen by the time the patient sits down.' },
      { i: 'rx', t: 'Top-200 Rx templates', d: 'Pre-built scripts for the top 200 conditions. Sign with one tap, edit when needed.' },
      { i: 'records', t: 'Chronic care timelines', d: 'HTN, diabetes, COPD — one timeline view with target bands and overdue checks.' },
      { i: 'scan', t: 'Family history', d: 'A clean visual family tree with hereditary tagging. Builds itself from each visit.' },
      { i: 'whatsapp', t: 'Post-visit summary', d: 'Patients get a clean summary on WhatsApp before they get to the car park.' },
    ],
    workflowHead: 'A 10-minute OPD visit, end to end.',
    workflow: [
      { t: 'Walk-in or arrives', d: 'Receptionist tags severity. Patient enters queue with a live wait estimate.' },
      { t: 'Vitals captured', d: 'Nurse records BP, HR, weight on tablet. Flagged in red if outside the target band.' },
      { t: 'Doctor reviews', d: 'You see vitals, last visit, allergies and the suggested Rx template all on one screen.' },
      { t: 'Rx + visit notes', d: 'One tap to sign Rx. Voice-dictate visit notes or type in SOAP.' },
      { t: 'Summary delivered', d: 'WhatsApp summary, follow-up booked, billing reconciled before they leave.' },
    ],
    pricingHead: 'A real solo GP, $24 a month.',
    pricingBlurb: 'Most solo GPs run on Starter plus the essentials. Pay nothing for the chronic-care features you don\'t use yet.',
    pricingLabel: 'Solo GP, ~25 patients/day',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Digital prescriptions', '$6/mo'],
      ['QR patient card', '$4/mo'],
      ['Vitals & charts', '$5/mo'],
      ['Billing & invoices', '$9/mo'],
    ],
    pricingTotal: 24,
    testimonialsHead: 'What GPs say.',
    testimonials: [
      { n: 'Dr. Aarav Sharma', s: 'Mumbai, India', q: 'I switched from paper in two weekends. The QR cards alone cut my check-in time by 80%. My nurses cried with joy.' },
      { n: 'Dr. Ben Carter', s: 'Bristol, UK', q: 'Calm, fast, no junk. It feels like a tool made for clinicians, not for the people selling to clinicians.' },
      { n: 'Dr. Liang Wei', s: 'Singapore', q: 'I see 40 patients a day. The vitals trend chart catches things I would have missed flipping through paper.' },
    ],
    migrationBlurb: 'Coming from EMRs, paper, or a tangle of spreadsheets — we move it all. Most clinics are live in under a week.',
    migrateFrom: ['Practo', 'Drchrono', 'Athenahealth', 'eClinicalWorks', 'EMIS', 'SystmOne', 'Cliniko', 'SimplePractice', 'Excel / CSV', 'Paper register'],
    ctaTitle: 'Run a GP practice that respects your time.',
    ctaSub: 'Start free. Add modules when your day demands it.',
  },

  homeo: {
    id: 'homeo', label: 'Homeopaths', mockKey: 'homeo',
    href: 'for-homeopaths.html',
    headline: { before: 'Built for ', accent: 'case taking', after: ', not just clicking.' },
    heroBlurb: 'Long-form repertory notes, a 3,200-remedy database, potency picker, and antidote warnings. The first software a homeopath might actually love.',
    heroProof: ['620 homeo clinics', '11 countries', 'From $13/mo'],
    stats: [
      { v: '3,200', l: 'Remedies in database' },
      { v: '15 min', l: 'Saved per case' },
      { v: '6 mo', l: 'Follow-up tracking' },
      { v: '4.9', l: 'Avg homeopath rating' },
    ],
    featsHead: { h: 'A clinic OS that speaks homeopathy.', h2: 'Not a generic record system in disguise.' },
    feats: [
      { i: 'flask', t: 'Remedy database', d: '3,200 remedies with potency, antidotes, miasm tags and Materia Medica references. Searchable in seconds.' },
      { i: 'records', t: 'Repertory case taking', d: 'A real long-form template — mental generals, physical generals, particulars, modalities — built in.' },
      { i: 'bolt', t: 'Potency picker', d: '6X to 1M with a sliding scale. Notes on prescribed potency travel with the case.' },
      { i: 'shield', t: 'Antidote engine', d: 'Coffee, camphor, peppermint — the system warns when antidotes appear in another part of the chart.' },
      { i: 'cal', t: 'Follow-up scheduler', d: 'Three weeks, six weeks, three months — your follow-up cadence built into the calendar.' },
      { i: 'graph', t: 'Case history view', d: 'Every remedy ever given, every reaction, every modality change — in one scrollable timeline.' },
    ],
    workflowHead: 'From first interview to long-term follow-up.',
    workflow: [
      { t: 'First interview', d: 'Long-form template loads. You take a 60-minute case with mental, physical, particular sections.' },
      { t: 'Repertorize', d: 'Pick rubrics from the case. The remedy DB suggests top matches with confidence scoring.' },
      { t: 'Prescribe', d: 'Select remedy, potency, schedule. Antidote warnings surface if anything conflicts.' },
      { t: 'Follow-up books itself', d: 'System schedules 3-week and 6-week follow-ups, sends WhatsApp reminders.' },
      { t: 'Track over months', d: 'Every change rolled into a timeline. You see the case story at a glance.' },
    ],
    pricingHead: 'A real homeopath, $22 a month.',
    pricingBlurb: 'Most solo homeopaths run on Starter plus the remedy database. The rest is free.',
    pricingLabel: 'Solo homeopath',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Remedy database', '$7/mo'],
      ['Digital prescriptions', '$6/mo'],
      ['Billing & invoices', '$9/mo'],
    ],
    pricingTotal: 22,
    testimonialsHead: 'What homeopaths say.',
    testimonials: [
      { n: 'Dr. Priya Iyer', s: 'Pune, India', q: 'Finally, software that knows what a repertory case-taking sheet looks like. The remedy DB is shockingly thorough.' },
      { n: 'Dr. Elena Costa', s: 'Lisbon, Portugal', q: 'The antidote warnings have saved me three times in the first month. Worth the cost a hundred times over.' },
      { n: 'Dr. Rohit Kapoor', s: 'Delhi, India', q: 'Long-form case notes that don\'t fight me. I take cases the way I was taught, not the way the software demands.' },
    ],
    migrationBlurb: 'Most homeopaths come from paper case books or Word documents. We OCR your old cases and import them, attribute by attribute.',
    migrateFrom: ['Paper case books', 'Word / PDF cases', 'Practo', 'Cliniko', 'HomeoSoft', 'Excel / CSV', 'RADAR exports'],
    ctaTitle: 'Run a homeo practice that respects the case.',
    ctaSub: 'Start free. Turn on the remedy DB when you take your first case.',
  },

  derma: {
    id: 'derma', label: 'Dermatologists', mockKey: 'derma',
    href: 'for-dermatologists.html',
    headline: { before: 'Before, after, and ', accent: 'everything', after: ' in between.' },
    heroBlurb: 'Photo timelines per body area, side-by-side compare, lesion measurement, and consent forms — built for skin, not bent into it.',
    heroProof: ['380 derma clinics', '18 countries', 'From $20/mo'],
    stats: [
      { v: '+44%', l: 'Patient retention' },
      { v: '−60%', l: 'Photo admin time' },
      { v: '3D', l: 'Body-map zones' },
      { v: '4.9', l: 'Avg derma rating' },
    ],
    featsHead: { h: 'The visual tools dermatology needs.', h2: "Nothing more, nothing less." },
    feats: [
      { i: 'image', t: 'Body-map photo logging', d: 'Tap a body region, attach photos. They organize themselves by area and date forever.' },
      { i: 'scan', t: 'Side-by-side compare', d: 'Pull any two visits next to each other. Slide to wipe between. Patients see progress in 5 seconds.' },
      { i: 'chart', t: 'Lesion measurement', d: 'Draw a contour, get area, diameter, asymmetry. Track all four ABCD criteria per lesion.' },
      { i: 'records', t: 'Procedure-linked consent', d: 'Each procedure brings its consent form. Patient signs on tablet, signed PDF lives in the chart.' },
      { i: 'leaf', t: 'Topical & systemic plans', d: 'Sequenced treatment plans with photos at each phase. Auto-reminders for application steps.' },
      { i: 'rx', t: 'Derma-aware Rx', d: 'Steroid potency ladder, biologics scheduling, retinoid pregnancy warnings built into the workflow.' },
    ],
    workflowHead: 'From first photo to twelve-month outcome.',
    workflow: [
      { t: 'New patient, body map', d: 'Tap the regions of concern. Attach phone photos directly to those zones.' },
      { t: 'Diagnose & plan', d: 'Make the diagnosis, link to procedure consent. Patient signs on the tablet.' },
      { t: 'Procedure or Rx', d: 'Procedure room: log start/end, materials. Or send the topical Rx via WhatsApp.' },
      { t: 'Follow-up photos', d: 'Each follow-up auto-aligns photos to the same body-map zone. No more "wait, what angle was this?"' },
      { t: 'Compare & decide', d: 'Side-by-side wipe between any two visits. Adjust plan, repeat.' },
    ],
    pricingHead: 'A real derma clinic, $34 a month.',
    pricingBlurb: 'Most dermatologists run the skin imaging module plus the essentials.',
    pricingLabel: 'Solo dermatologist',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Skin imaging module', '$11/mo'],
      ['Digital prescriptions', '$6/mo'],
      ['Vitals & charts', '$5/mo'],
      ['Billing & invoices', '$9/mo'],
      ['Diet plans', '$3/mo (add-on)'],
    ],
    pricingTotal: 34,
    testimonialsHead: 'What dermatologists say.',
    testimonials: [
      { n: 'Dr. Sofia Marín', s: 'Madrid, Spain', q: 'The before/after compare convinced me to stay. The pricing convinced my accountant. We pay €34/month for what we use.' },
      { n: 'Dr. Hannah Lin', s: 'Sydney, Australia', q: 'The lesion measurement tool is genuinely better than what we used at the hospital. Patients trust the numbers.' },
      { n: 'Dr. Olu Adebayo', s: 'Lagos, Nigeria', q: 'My patients see the progress and stay the full course. Retention jumped from 60% to 88% in six months.' },
    ],
    migrationBlurb: 'Skin photos live everywhere — phones, drives, EMRs. We pull them all into the body-map, sorted by date and region.',
    migrateFrom: ['NextGen', 'ModMed', 'Mirror Medical', 'Canfield', 'Phone camera roll', 'Google Photos', 'Practo', 'Cliniko', 'Excel / CSV'],
    ctaTitle: 'Run a derma clinic that shows the change.',
    ctaSub: 'Start free. Turn on skin imaging when your first patient walks in.',
  },

  peds: {
    id: 'peds', label: 'Pediatricians', mockKey: 'peds',
    href: 'for-pediatricians.html',
    headline: { before: 'Watch them grow, on ', accent: 'real percentile', after: ' curves.' },
    heroBlurb: 'WHO growth charts, vaccination scheduler, weight-based dosing, parent-facing summaries — designed around how kids actually grow.',
    heroProof: ['540 peds clinics', '22 countries', 'From $19/mo'],
    stats: [
      { v: '+38%', l: 'Vaccine on-time rate' },
      { v: '0', l: 'Dosing errors logged' },
      { v: '12 mo', l: 'Growth tracking' },
      { v: '4.9', l: 'Avg parent rating' },
    ],
    featsHead: { h: 'Pediatric care, tooled properly.', h2: 'For every child, from 0 to 18.' },
    feats: [
      { i: 'sprout', t: 'WHO growth charts', d: 'Weight, height, head circumference, BMI — every visit plotted on WHO percentile bands.' },
      { i: 'cal', t: 'Vaccine scheduler', d: 'Country-specific schedules. Reminders go to the parent\'s WhatsApp 30 days before each dose.' },
      { i: 'rx', t: 'Weight-based dosing', d: 'Enter the child\'s weight; doses calculate themselves. Pediatric range warnings catch outliers.' },
      { i: 'whatsapp', t: 'Parent-facing summaries', d: 'After each visit, parents get a clean summary in plain language with next steps.' },
      { i: 'records', t: 'Developmental milestones', d: 'Auto-prompted milestone checks at 2/4/6/9/12/18/24-month visits. Track delays cleanly.' },
      { i: 'shield', t: 'Allergy & feeding flags', d: 'Penicillin, peanut, lactose, gluten — flagged across every Rx and procedure.' },
    ],
    workflowHead: "Every well-visit, the same five-step rhythm.",
    workflow: [
      { t: 'Weigh & measure', d: 'Nurse enters weight, height, head circumference on tablet. Auto-plotted on percentile curve.' },
      { t: 'Milestone check', d: 'System prompts the right age-appropriate milestones. You tap "met" or add notes.' },
      { t: 'Vaccine review', d: 'Schedule shows what\'s due today, what\'s coming up next month, what got missed.' },
      { t: 'Rx with auto-dose', d: 'Type the drug name; dose, frequency, and duration calculate from the latest weight.' },
      { t: 'Parent summary', d: 'WhatsApp summary goes out: "You saw Dr. Okonkwo today. Sneha is at the 62nd percentile…"' },
    ],
    pricingHead: 'A real peds clinic, $25 a month.',
    pricingBlurb: 'Most pediatricians run the growth-chart module plus the basics.',
    pricingLabel: 'Solo pediatrician',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Growth charts module', '$5/mo'],
      ['Digital prescriptions', '$6/mo'],
      ['QR patient card', '$4/mo'],
      ['Vitals & charts', '$5/mo'],
      ['Billing & invoices (lite)', '$5/mo'],
    ],
    pricingTotal: 25,
    testimonialsHead: 'What pediatricians say.',
    testimonials: [
      { n: 'Dr. Amara Okonkwo', s: 'Lagos, Nigeria', q: 'Parents love the weight-based dosing and the WhatsApp summary. I love that I no longer fight a spreadsheet.' },
      { n: 'Dr. Mei-Lin Chen', s: 'Taipei, Taiwan', q: 'The vaccine reminders single-handedly raised our on-time rate from 64% to 91%. My nurses sleep better.' },
      { n: 'Dr. Andrés Vega', s: 'Bogotá, Colombia', q: 'My patients\' parents are now genuinely invested in their child\'s growth chart. They show me at every visit.' },
    ],
    migrationBlurb: 'Pediatric records live in immunization registries, EMRs, and growth-tracking apps. We pull them all into one timeline.',
    migrateFrom: ['Practo', 'eClinicalWorks', 'OfficePractic', 'Pediatric Practice Manager', 'Govt. immunization registry', 'Excel / CSV', 'Paper card'],
    ctaTitle: 'Run a peds clinic that grows with every child.',
    ctaSub: 'Start free. Turn on growth charts at the first well-visit.',
  },

  physio: {
    id: 'physio', label: 'Physiotherapists', mockKey: 'physio',
    href: 'for-physiotherapists.html',
    headline: { before: 'Programs your patients ', accent: 'actually', after: ' follow.' },
    heroBlurb: 'Build exercise programs from a 600-video library and send them to your patient as a follow-along plan on WhatsApp. Track adherence and outcomes.',
    heroProof: ['490 physio clinics', '19 countries', 'From $17/mo'],
    stats: [
      { v: '600+', l: 'Exercise videos' },
      { v: '+62%', l: 'Home-program adherence' },
      { v: '8', l: 'Outcome scales' },
      { v: '4.8', l: 'Avg physio rating' },
    ],
    featsHead: { h: 'Tools for clinic-and-home physiotherapy.', h2: 'Built for adherence, not paperwork.' },
    feats: [
      { i: 'video', t: 'Exercise video library', d: '600+ HD videos, multiple angles, voice-over in 8 languages. Filter by region, condition, equipment.' },
      { i: 'cal', t: 'Weekly program builder', d: 'Drag exercises into a 7-day grid. Sets, reps, hold time, rest — set once, sent everywhere.' },
      { i: 'whatsapp', t: 'Patient follow-along', d: 'Patient sees the day\'s program on WhatsApp with a tap-to-play video. Check off as they go.' },
      { i: 'chart', t: 'Outcome scales', d: 'ODI, NDI, DASH, Roland-Morris, SF-36 — auto-scored, plotted over time.' },
      { i: 'graph', t: 'Adherence tracking', d: 'See who did Monday\'s exercises and who didn\'t. Auto-nudge skipped sessions.' },
      { i: 'records', t: 'Pain & motion logs', d: 'VAS pain score and ROM measurements per visit, plotted alongside outcome scales.' },
    ],
    workflowHead: 'From first assessment to discharge.',
    workflow: [
      { t: 'Assess & score', d: 'Run a baseline ODI/NDI. Record VAS, ROM. Photo or video your manual assessment.' },
      { t: 'Build the program', d: 'Drag exercises from the library into a weekly grid. Set reps, hold, intensity.' },
      { t: 'Send to patient', d: 'WhatsApp link. Patient opens it on the bus home — videos play, exercises check off.' },
      { t: 'Track adherence', d: 'Daily and weekly view: who did what, who skipped, who reported pain.' },
      { t: 'Reassess at week 4', d: 'Rerun the scales. Outcome plot side-by-side with adherence. Adjust the program.' },
    ],
    pricingHead: 'A real physio practice, $22 a month.',
    pricingBlurb: 'Solo physios run on Starter plus the exercise program module.',
    pricingLabel: 'Solo physiotherapist',
    pricingItems: [
      ['Starter plan', 'Free'],
      ['Exercise plans module', '$8/mo'],
      ['Vitals & charts', '$5/mo'],
      ['Billing & invoices', '$9/mo'],
    ],
    pricingTotal: 22,
    testimonialsHead: 'What physios say.',
    testimonials: [
      { n: 'Dr. Maya Patel', s: 'Bristol, UK', q: 'My patients actually do their home programs now. Adherence went from 30% to 78% in three months. That\'s the whole job.' },
      { n: 'Dr. Tomás Silva', s: 'São Paulo, Brazil', q: 'The Portuguese voice-over in the videos changed everything. My patients trust the program because they can hear instructions in their language.' },
      { n: 'Dr. Hyun-woo Park', s: 'Seoul, South Korea', q: 'I run a sports physio clinic. The outcome scales plus video feedback let me discharge confidently.' },
    ],
    migrationBlurb: 'Physio records are messy — assessment PDFs, video files, paper programs. We import everything and re-link it by patient.',
    migrateFrom: ['Cliniko', 'PracticeHub', 'Jane App', 'Physitrack', 'TheraNest', 'Google Drive videos', 'Excel / CSV', 'Paper programs'],
    ctaTitle: 'Run a physio practice your patients stick with.',
    ctaSub: 'Start free. Turn on exercise plans when you write your first program.',
  },
};
